export const DATA = {
  company: {
    name_ar: "سين أوتوميشن", name_en: "Seen Automation",
    tagline_ar: "أتمتة. ارتقاء. حلال.", tagline_en: "Automate. Elevate. Halal.",
    vision_ar: "قيادة سوق أتمتة الذكاء الاصطناعي في العالم العربي عبر حلول مرئية مستقلة، حلال 100%.",
    vision_en: "Leading the AI automation market in the Arab world through independent, 100% Halal visual solutions.",
    mission_ar: "تحرير الطاقات البشرية من الروتين عبر أتمتة ذكية، حلال، ومنخفضة التكلفة.",
    mission_en: "Liberating human potential from routine through intelligent, Halal, cost-effective automation.",
    founder: {
      name: "عمر محمد جميل باعبدالله", name_en: "Omar Mohammed Jamil Baabdullah",
      role_ar: "المؤسس التشغيلي ومعمار الأنظمة", role_en: "Operational Founder & Systems Architect",
      bio_ar: "مهندس ميكانيكي خريج SEGi University في ماليزيا، بخبرة ميدانية في SABIC. متخصص في تحسين العمليات الصناعية وسلاسل الإمداد.",
      bio_en: "Mechanical engineer, SEGi University graduate, with SABIC field experience. Specialized in industrial process optimization.",
    },
    entity: "Malaysian Sdn Bhd", hq_ar: "أونلاين / عالمي", hq_en: "Online / Worldwide",
  },
  ask: { amount: 82500, amount_usd: 22000, structure_ar: "مضاربة شرعية (AAOIFI)", structure_en: "Sharia-compliant Mudarabah", phase1: 15, phase2: 15, phase2_months: 36, buyout_months: 24, buyout_multiple: 1.5, max_years: 15 },
  market: {
    tam: { value: 3.5, unit: "B", label_ar: "السوق الكلي", label_en: "Total Addressable Market" },
    sam: { value: 1.95, unit: "B", label_ar: "السوق القابل للخدمة", label_en: "Serviceable Available Market" },
    som: { value: 320, unit: "K", label_ar: "السوق القابل للاستحواذ (Y1)", label_en: "Serviceable Obtainable (Y1)" },
  },
  kpis: [
    { label_ar: "الإيراد الشهري Y1", label_en: "MRR Y1", value: "32K", unit: "SAR", color: "emerald" },
    { label_ar: "الإيراد الشهري Y3", label_en: "MRR Y3", value: "78K", unit: "SAR", color: "gold" },
    { label_ar: "LTV:CAC", label_en: "LTV:CAC", value: "19.3x", unit: "", color: "accent" },
    { label_ar: "نقطة التعادل", label_en: "Break-even", value: "2", unit: "شهر", color: "emerald" },
    { label_ar: "عملاء Y1", label_en: "Customers Y1", value: "20", unit: "", color: "gold" },
    { label_ar: "عملاء Y3", label_en: "Customers Y3", value: "50", unit: "", color: "accent" },
  ],
  financials: {
    arpu: 1600, churn: 6, cac: 1500, margin: 70, fixedCosts: 3500, newCustomers: 2.3,
    useOfFunds: {
      operations: { percent: 60, amount: 49500, label_ar: "عمليات وتوظيف", label_en: "Operations & Hiring" },
      marketing: { percent: 40, amount: 33000, label_ar: "تسويق واستحواذ", label_en: "Marketing & Acquisition" },
    },
    projections: {
      y1: { revenue: 384000, costs: 106800, profit: 277200 },
      y2: { revenue: 600000, costs: 144000, profit: 456000 },
      y3: { revenue: 936000, costs: 195000, profit: 741000 },
    },
  },
  packages: [
    { name: "Starter", setup_min: 3000, setup_max: 5000, monthly_min: 600, monthly_max: 1000, sla: "30 دقيقة", workflows: 1, features: ["Workflow واحد", "قناة واحدة", "تقرير شهري", "Error Node أساسي"] },
    { name: "Growth", setup_min: 6000, setup_max: 10000, monthly_min: 1200, monthly_max: 2000, sla: "15 دقيقة", workflows: 3, features: ["3 Workflows", "قنوات متعددة", "لوحة تحكم", "تكامل API", "SLA موثق"] },
    { name: "Enterprise", setup_min: 15000, setup_max: 25000, monthly_min: 3000, monthly_max: 5000, sla: "5 دقائق", workflows: 10, features: ["10+ Workflows", "Self-Hosted", "دعم VIP", "مدير حساب", "SLA 99.5%"] },
    { name: "Lead-Gen", setup_min: 1000, setup_max: 3000, monthly_min: 300, monthly_max: 600, sla: "30 دقيقة", workflows: 1, features: ["Workflow بسيط", "3 إحالات/سنة", "لا نرفض بسبب الميزانية"] },
  ],
  competitors: [
    { name: "UiPath", price: "SAR 10K-50K", specialty_ar: "جزئي", halal: false, weakness_ar: "معقد + مكلف" },
    { name: "PROVEN", price: "SAR 75K+", specialty_ar: "لا", halal: false, weakness_ar: "أسعار مرتفعة" },
    { name: "Hivekind", price: "$50-99/hr", specialty_ar: "لا", halal: false, weakness_ar: "لا تخصص هندسي" },
    { name: "Seen", price: "SAR 600-5K", specialty_ar: "هندسي ✅", halal: true, weakness_ar: "—" },
  ],
  sectors: [
    { id: "eng", name_ar: "الهندسة", name_en: "Engineering", status: "active", desc_ar: "أتمتة RFIs، QOO، Submittals للمكاتب الهندسية.", desc_en: "Automating RFIs, QOO, Submittals for engineering firms.", timeline: "Q1 2026", target_clients: 20 },
    { id: "med", name_ar: "الطب", name_en: "Medical", status: "upcoming", desc_ar: "أتمتة السجلات الطبية والتقارير السريرية.", desc_en: "Automating medical records and clinical reports.", timeline: "Q3 2026", target_clients: 10 },
    { id: "leg", name_ar: "القانون", name_en: "Legal", status: "upcoming", desc_ar: "مراجعة العقود وصياغة المستندات القانونية.", desc_en: "Contract review and legal document drafting.", timeline: "Q4 2026", target_clients: 8 },
    { id: "edu", name_ar: "التعليم", name_en: "Education", status: "upcoming", desc_ar: "أتمتة العمليات الإدارية وتقييم الطلاب.", desc_en: "Automating admin operations and student assessment.", timeline: "Q1 2027", target_clients: 12 },
    { id: "com", name_ar: "التجارة", name_en: "Commerce", status: "upcoming", desc_ar: "أتمتة سلاسل الإمداد والفوترة الإلكترونية.", desc_en: "Automating supply chains and e-invoicing.", timeline: "Q2 2027", target_clients: 15 },
  ],
  risks: [
    { name_ar: "تأخر اعتماد العميل", name_en: "Client approval delays", prob: "high", impact: "medium", mitigation_ar: "بنود SLA واضحة مع جدول زمني ملزم", mitigation_en: "Clear SLA with binding timeline" },
    { name_ar: "تغير متطلبات المشروع", name_en: "Scope creep", prob: "medium", impact: "high", mitigation_ar: "نموذج Change Request رسمي", mitigation_en: "Formal Change Request model" },
    { name_ar: "فشل API خارجي", name_en: "External API failure", prob: "low", impact: "high", mitigation_ar: "Fallback mechanisms + Error Node", mitigation_en: "Fallback mechanisms + Error Node" },
    { name_ar: "منافسة أسعار", name_en: "Price competition", prob: "high", impact: "medium", mitigation_ar: "التركيز على القيمة والـ ROI", mitigation_en: "Focus on value & ROI" },
    { name_ar: "نقص الكفاءات", name_en: "Talent shortage", prob: "medium", impact: "medium", mitigation_ar: "الأتمتة الذاتية + Freelancers", mitigation_en: "Self-automation + freelancers" },
    { name_ar: "تغير تنظيمي", name_en: "Regulatory changes", prob: "low", impact: "high", mitigation_ar: "مراجعة قانونية ربع سنوية", mitigation_en: "Quarterly legal review" },
  ],
  hardware: {
    laptops: [
      { category: "Entry-Level", specs: "Ryzen AI 7, 16GB", price: "$700-900", ai: "4B-8B" },
      { category: "Mid-Range", specs: "Ryzen AI 9, 32GB", price: "$1,100-1,500", ai: "7B-13B" },
      { category: "High-End", specs: "RTX 5070, 64GB", price: "$1,600-2,500", ai: "13B-30B" },
      { category: "Extreme", specs: "RTX 5090 24GB, 128GB", price: "$3,500-7,000", ai: "30B-70B" },
      { category: "Unified Memory ⭐", specs: "Ryzen AI Max+ 395, 128GB", price: "$3,000-4,000", ai: "70B-120B" },
    ],
    minipc: [
      { category: "Entry", specs: "Ryzen 7, 32GB", price: "$700-900" },
      { category: "Mid-Range", specs: "Ryzen AI 9 HX, 32GB", price: "$1,100-1,700" },
      { category: "High-End", specs: "Ryzen AI Max+, 128GB", price: "$2,600-4,000" },
      { category: "Ultra GPU", specs: "RTX 5070/5090", price: "$1,600-3,500" },
      { category: "Extreme", specs: "RTX PRO 6000", price: "$6,000-12,000" },
    ],
    scenario: {
      name_ar: "Unified Memory", name_en: "Unified Memory",
      laptop: "HP ZBook Ultra G1a 14 — Ryzen AI Max+ PRO 395, 128GB", laptop_price: 3500,
      minipc: "Minisforum MS-S1 Max — Ryzen AI Max+ 395, 128GB, 2TB", minipc_price: 3639,
      accessories: "شاشات + Docking + UPS", accessories_en: "Displays + Docking + UPS", accessories_price: 1958,
      total: 10197, remaining: 1803, budget: 12000,
    },
  },
  roadmap: [
    { phase_ar: "💡 لحظة الفكرة", phase_en: "💡 Idea Born", date_ar: "يناير 2026", date_en: "Jan 2026", desc_ar: "ولدت الفكرة من ملاحظة الاختناقات في المكاتب الهندسية.", desc_en: "Idea born from observing engineering bottlenecks." },
    { phase_ar: "🔬 البحث والتحقق", phase_en: "🔬 Research", date_ar: "فبراير-مارس 2026", date_en: "Feb-Mar 2026", desc_ar: "دراسة السوق وتحديد الفجوة الذهبية.", desc_en: "Market study and golden gap identification." },
    { phase_ar: "📚 بناء المستودع", phase_en: "📚 KB Build", date_ar: "أبريل-يونيو 2026", date_en: "Apr-Jun 2026", desc_ar: "إنشاء 49 ملفاً استراتيجياً.", desc_en: "Created 49 strategic documents." },
    { phase_ar: "🏛️ التأسيس القانوني", phase_en: "🏛️ Legal Setup", date_ar: "يوليو 2026", date_en: "Jul 2026", desc_ar: "تسجيل الكيان في ماليزيا.", desc_en: "Entity registration in Malaysia." },
    { phase_ar: "🚀 الإطلاق", phase_en: "🚀 Launch", date_ar: "أغسطس 2026", date_en: "Aug 2026", desc_ar: "إطلاق بوابة المستثمرين.", desc_en: "Investor portal launch." },
    { phase_ar: "⭐ أول عميل", phase_en: "⭐ First Client", date_ar: "Q3 2026", date_en: "Q3 2026", desc_ar: "أول 5 عملاء هندسيين.", desc_en: "First 5 engineering clients." },
    { phase_ar: "🌍 التوسع", phase_en: "🌍 Expansion", date_ar: "السنة 2", date_en: "Year 2", desc_ar: "رمح القانون والتعليم.", desc_en: "Legal and Education spears." },
    { phase_ar: "🏆 القيادة", phase_en: "🏆 Leadership", date_ar: "السنة 3", date_en: "Year 3", desc_ar: "Micro-SaaS و 80+ عميل.", desc_en: "Micro-SaaS and 80+ clients." },
  ],
  businessPlan: [
    { title_ar: "الملخص التنفيذي", title_en: "Executive Summary", content_ar: "Seen Automation وكالة أتمتة AI حلال 100%، تبدأ بقطاع الهندسة كبوابة ذهبية. نطلب SAR 82,500 عبر مضاربة شرعية.", content_en: "Seen Automation is a 100% Halal AI automation agency starting with engineering. Seeking SAR 82,500 via Sharia Mudarabah." },
    { title_ar: "وصف الشركة", title_en: "Company Description", content_ar: "الكيان: Malaysian Sdn Bhd. الرؤية: قيادة سوق الأتمتة العربي. الاستراتيجية: الهندسة كبوابة، ثم التوسع، ثم Micro-SaaS.", content_en: "Entity: Malaysian Sdn Bhd. Vision: Leading Arab automation market. Strategy: Engineering gateway, then expansion, then Micro-SaaS." },
    { title_ar: "تحليل السوق", title_en: "Market Analysis", content_ar: "السعودي: TAM $223M. الماليزي: TAM $462M. CAGR 14.9-28.4%. محركات: رؤية 2030، +56.25% إنفاق AI.", content_en: "Saudi: TAM $223M. Malaysian: TAM $462M. CAGR 14.9-28.4%. Drivers: Vision 2030, +56.25% AI spending." },
    { title_ar: "تحليل المنافسين", title_en: "Competitive Analysis", content_ar: "10 منافسين. ميزة Seen: سعر أقل 10x، تخصص هندسي، حلال 100%، SLA 5-30 دقيقة.", content_en: "10 competitors. Seen advantages: 10x lower price, engineering specialization, 100% Halal, SLA 5-30 min." },
    { title_ar: "المنتج والخدمات", title_en: "Products & Services", content_ar: "4 باقات: Starter (SAR 600-1K)، Growth (SAR 1.2-2K)، Enterprise (SAR 3-5K)، Lead-Gen (SAR 300-600).", content_en: "4 packages: Starter (SAR 600-1K), Growth (SAR 1.2-2K), Enterprise (SAR 3-5K), Lead-Gen (SAR 300-600)." },
    { title_ar: "التسويق والمبيعات", title_en: "Marketing & Sales", content_ar: "Landing Bot → Report → Confirmation Call. Close Rate 25-35%. Sales Cycle 3-7 أيام.", content_en: "Landing Bot → Report → Confirmation Call. Close Rate 25-35%. Sales Cycle 3-7 days." },
    { title_ar: "العمليات", title_en: "Operations", content_ar: "دورة 2-4 أسابيع. Search-Before-Build يوفر 60-80% من الوقت. 26 SOP.", content_en: "2-4 week cycle. Search-Before-Build saves 60-80% time. 26 SOPs." },
    { title_ar: "الفريق", title_en: "Team", content_ar: "عمر باعبدالله — المؤسس. أحمد — الشريك القانوني.", content_en: "Omar Baabdullah — Founder. Ahmed — Legal Partner." },
    { title_ar: "النموذج المالي", title_en: "Financial Model", content_ar: "LTV:CAC 19.3x. نقطة التعادل شهر 2. هامش 70-80%.", content_en: "LTV:CAC 19.3x. Break-even month 2. Margin 70-80%." },
    { title_ar: "المخاطر", title_en: "Risks", content_ar: "10 مخاطر موثقة. بروتوكول أمني شامل + تشفير + مراجعة قانونية.", content_en: "10 documented risks. Comprehensive security + encryption + legal review." },
  ],
    pitchSlides: [
    { title_ar: "الغلاف", title_en: "Cover", content_ar: "Seen Automation\nAutomate. Elevate. Halal.", content_en: "Seen Automation\nAutomate. Elevate. Halal." },
    { title_ar: "المشكلة", title_en: "Problem", content_ar: "7.6 ساعة/أسبوع مهدرة\n67.6% أخطاء رسومات", content_en: "7.6 hours/week wasted\n67.6% drawing errors" },
    { title_ar: "الحل", title_en: "Solution", content_ar: "AI Backend Pipelines\nZero-Friction", content_en: "AI Backend Pipelines\nZero-Friction" },
    { title_ar: "لماذا الآن", title_en: "Why Now", content_ar: "Vision 2030\n+56.25% AI spending", content_en: "Vision 2030\n+56.25% AI spending" },
    { title_ar: "السوق", title_en: "Market", content_ar: "TAM $3.5B\nSAM $1.95B\nSOM $320K", content_en: "TAM $3.5B\nSAM $1.95B\nSOM $320K" },
    { title_ar: "النموذج", title_en: "Model", content_ar: "SAR 600-5K/شهر\nهامش 70-80%", content_en: "SAR 600-5K/mo\n70-80% margin" },
    { title_ar: "الجاهزية", title_en: "Readiness", content_ar: "49 ملف\nبروتوكول أمني", content_en: "49 docs\nSecurity protocol" },
    { title_ar: "المنافسون", title_en: "Competitors", content_ar: "Seen: SAR 600-5K + حلال", content_en: "Seen: SAR 600-5K + Halal" },
    { title_ar: "الميزة", title_en: "Edge", content_ar: "حلال 100%\nSLA 5-30 دقيقة", content_en: "100% Halal\nSLA 5-30 min" },
    { title_ar: "الدخول", title_en: "GTM", content_ar: "Landing Bot\nClose 25-35%", content_en: "Landing Bot\nClose 25-35%" },
    { title_ar: "الفريق", title_en: "Team", content_ar: "عمر باعبدالله\nSEGi + SABIC", content_en: "Omar Baabdullah\nSEGi + SABIC" },
    { title_ar: "المالية", title_en: "Financials", content_ar: "Y3: SAR 936K\n80 عميل", content_en: "Y3: SAR 936K\n80 clients" },
    { title_ar: "الطلب", title_en: "Ask", content_ar: "SAR 82,500\nمضاربة شرعية", content_en: "SAR 82,500\nSharia Mudarabah" },
    { title_ar: "الرؤية", title_en: "Vision", content_ar: "Y5: 200+ عميل\n$2M+ ARR", content_en: "Y5: 200+ clients\n$2M+ ARR" },
  ],,
  securityHighlights: { attacks: 25, hallucinationTests: 100, encryption: "AES-256 + TLS 1.3" },
  checklists: {
    investorReady: [
      { label_ar: "خطة عمل شاملة", label_en: "Comprehensive business plan", done: true },
      { label_ar: "نموذج مالي تفاعلي", label_en: "Interactive financial model", done: true },
      { label_ar: "Pitch Deck (14 شريحة)", label_en: "Pitch Deck (14 slides)", done: true },
      { label_ar: "تحليل المنافسين", label_en: "Competitor analysis", done: true },
      { label_ar: "5 قطاعات مستهدفة", label_en: "5 target sectors", done: true },
      { label_ar: "خريطة طريق 36 شهر", label_en: "36-month roadmap", done: true },
      { label_ar: "سجل مخاطر", label_en: "Risk register", done: true },
      { label_ar: "مواصفات عتاد", label_en: "Hardware specs", done: true },
      { label_ar: "مضاربة شرعية", label_en: "Sharia Mudarabah", done: true },
      { label_ar: "بروتوكول أمني", label_en: "Security protocol", done: true },
    ],
    dueDiligence: [
      { label_ar: "NDA Template", label_en: "NDA Template", done: true },
      { label_ar: "MSA Template", label_en: "MSA Template", done: true },
      { label_ar: "SOW Template", label_en: "SOW Template", done: true },
      { label_ar: "SLA Template", label_en: "SLA Template", done: true },
      { label_ar: "DPA Template", label_en: "DPA Template", done: true },
      { label_ar: "Unit Economics", label_en: "Unit Economics", done: true },
      { label_ar: "Market Positioning", label_en: "Market Positioning", done: true },
      { label_ar: "Halal Certification", label_en: "Halal Certification", done: true },
    ],
  },
};
