export const DATA = {
  company: {
    name_ar: "سين أوتوميشن",
    name_en: "Seen Automation AI Agency",
    founder: "عمر محمد جميل باعبدالله",
    founder_role: "المؤسس التشغيلي ومعمار الأنظمة",
    founder_bio: "مهندس ميكانيكي خريج SEGi University في ماليزيا، بخبرة ميدانية في الشركة السعودية للصناعات الكيميائية (SABIC). متخصص في تحسين العمليات الصناعية وسلاسل الإمداد، مع فهم عميق للاختناقات التشغيلية في الشركات الهندسية وكيفية تفكيك الأنظمة المعقدة لأتمتتها بذكاء.",
    tagline: "Automate. Elevate. Halal.",
    vision: "قيادة سوق أتمتة الذكاء الاصطناعي في العالم العربي عبر حلول مرئية مستقلة، حلال 100%.",
    mission: "تحرير الطاقات البشرية من الروتين عبر أتمتة ذكية، حلال، ومنخفضة التكلفة.",
    entity: "Malaysian Sdn Bhd (قيد التأسيس)",
    hq: "Online / Worldwide",
  },
  ask: 82500,
  ask_usd: 22000,
  tam: "3.5B", sam: "1.95B", som: "320K",
  mrrY1: 32000, mrrY3: 78000,
  arpu: 1600, churn: 6, cac: 1500, margin: 70,
  fixedCosts: 3500, newCustomers: 2.3,
  customersY1: 20, customersY3: 50, breakEven: 2,
  useOfFunds: { operations: 60, marketing: 40, opsAmount: 49500, mktAmount: 33000 },
  mudarabah: { phase1: 15, phase2: 15, buyoutMonths: 24, buyoutMultiple: 1.5, maxYears: 15 },
  
  kpis: [
    { label: "TAM", value: "$3.5B", sub: "السوق الكلي", color: "emerald" },
    { label: "SAM", value: "$1.95B", sub: "السوق القابل للخدمة", color: "gold" },
    { label: "SOM Y1", value: "$320K", sub: "السوق القابل للاستحواذ", color: "accent" },
    { label: "MRR Y1", value: "SAR 32,000", sub: "الإيراد الشهري المتكرر", color: "emerald" },
    { label: "LTV:CAC", value: "19.3x", sub: "كفاءة الاكتساب", color: "gold" },
    { label: "الطلب", value: "SAR 82,500", sub: "مضاربة شرعية", color: "accent" },
  ],

  packages: [
    { name: "Starter", setup: "3,000-5,000", monthly: "600-1,000", sla: "30 دقيقة", workflows: 1, channels: 1, features: ["Workflow واحد", "قناة تواصل واحدة", "تقرير شهري", "Error Node أساسي"] },
    { name: "Growth", setup: "6,000-10,000", monthly: "1,200-2,000", sla: "15 دقيقة", workflows: 3, channels: 3, features: ["3 Workflows متكاملة", "قنوات متعددة", "لوحة Looker Studio", "تكامل API", "SLA موثق"] },
    { name: "Enterprise", setup: "15,000-25,000", monthly: "3,000-5,000", sla: "5 دقائق", workflows: 10, channels: -1, features: ["10+ Workflows مخصصة", "Self-Hosted Option", "دعم VIP", "مدير حساب مخصص", "SLA 99.5% Uptime"] },
    { name: "Lead-Gen", setup: "1,000-3,000", monthly: "300-600", sla: "30 دقيقة", workflows: 1, channels: 1, features: ["Workflow بسيط", "3 إحالات/سنة", "لا نرفض بسبب الميزانية"] },
  ],

  competitors: [
    { name: "UiPath", price: "SAR 10K-50K", specialty: "جزئي", halal: false, weakness: "معقد + مكلف" },
    { name: "PROVEN Consult", price: "SAR 75K+", specialty: "لا", halal: false, weakness: "أسعار مرتفعة" },
    { name: "Hivekind", price: "$50-99/ساعة", specialty: "لا", halal: false, weakness: "لا تخصص هندسي" },
    { name: "Wakeb", price: "$25-49/ساعة", specialty: "لا", halal: false, weakness: "تركيز UAV فقط" },
    { name: "Calq", price: "مجاني-مدفوع", specialty: "نعم (AEC)", halal: false, weakness: "نطاق ضيق (BIM فقط)" },
    { name: "AIQ", price: "SAR 8,812/مستخدم", specialty: "نعم (طاقة)", halal: false, weakness: "طاقة فقط" },
    { name: "Elm", price: "حكومي", specialty: "جزئي", halal: false, weakness: "حكومي فقط" },
    { name: "aTeam Soft", price: "$15K-40K", specialty: "لا", halal: false, weakness: "لا تخصص" },
    { name: "Alwajeez", price: "SAR 7,999/شهر", specialty: "لا", halal: false, weakness: "حكومي" },
    { name: "Seen Automation", price: "SAR 600-5K", specialty: "نعم (هندسي)", halal: true, weakness: null },
  ],

  sectors: [
    { id: "eng", name: "Engineering", ar: "الهندسة", status: "active", desc: "أتمتة RFIs، QOO، Submittals، تقارير التقدم، وتنسيق التخصصات للمكاتب الهندسية الاستشارية.", timeline: "Q1 2026", clients: 20 },
    { id: "med", name: "Medical", ar: "الطب", status: "upcoming", desc: "أتمتة السجلات الطبية، التقارير السريرية، وجدولة المواعيد الذكية للعيادات والمستشفيات.", timeline: "Q3 2026", clients: 10 },
    { id: "leg", name: "Legal", ar: "القانون", status: "upcoming", desc: "مراجعة العقود تلقائياً، صياغة المستندات القانونية، وتحليل المخاطر التعاقدية.", timeline: "Q4 2026", clients: 8 },
    { id: "edu", name: "Education", ar: "التعليم", status: "upcoming", desc: "أتمتة العمليات الإدارية، تقييم الطلاب، وإدارة المحتوى التعليمي الرقمي.", timeline: "Q1 2027", clients: 12 },
    { id: "com", name: "Commerce", ar: "التجارة", status: "upcoming", desc: "أتمتة سلاسل الإمداد، إدارة المخازن، والفوترة الإلكترونية المتكاملة.", timeline: "Q2 2027", clients: 15 },
  ],

  risks: [
    { id: 1, name: "تأخر اعتماد العميل", prob: "عالي", impact: "متوسط", mitigation: "تضمين بنود SLA واضحة مع جدول زمني ملزم للاعتماد", color: "red" },
    { id: 2, name: "تغير متطلبات المشروع", prob: "متوسط", impact: "عالي", mitigation: "نموذج Change Request رسمي مع تسعير منفصل للتغييرات", color: "yellow" },
    { id: 3, name: "فشل تكامل API خارجي", prob: "منخفض", impact: "عالي", mitigation: "Fallback mechanisms + Error Node + مراقبة مستمرة", color: "green" },
    { id: 4, name: "تسرب بيانات العملاء", prob: "منخفض", impact: "عالي", mitigation: "تشفير AES-256 + TLS 1.3 + عزل Containers لكل عميل", color: "green" },
    { id: 5, name: "منافسة أسعار قوية", prob: "عالي", impact: "متوسط", mitigation: "التركيز على القيمة والـ ROI لا السعر + تخصص هندسي عميق", color: "red" },
    { id: 6, name: "نقص الكفاءات التقنية", prob: "متوسط", impact: "متوسط", mitigation: "الاعتماد على الأتمتة الذاتية + شبكة Freelancers موثوقين", color: "yellow" },
    { id: 7, name: "تغير تنظيمي (PDPL/GDPR)", prob: "منخفض", impact: "عالي", mitigation: "مراجعة قانونية ربع سنوية + DPA محدّث", color: "green" },
    { id: 8, name: "هلوسة النماذج (AI Hallucination)", prob: "متوسط", impact: "عالي", mitigation: "100 سؤال اختبار هلوسة + RAG صارم + مراجعة بشرية", color: "yellow" },
    { id: 9, name: "تأخر دفع الفواتير", prob: "متوسط", impact: "متوسط", mitigation: "دفع مقدم + بنود تأخير حلال (خصم لا فائدة)", color: "yellow" },
    { id: 10, name: "فقدان النسخ الاحتياطي", prob: "منخفض", impact: "عالي", mitigation: "نسخ يومية مشفرة + اختبار استعادة أسبوعي + Offsite Backup", color: "green" },
  ],

  hardware: {
    laptops: [
      { category: "Entry-Level", specs: "Ryzen AI 7 / Ultra 5, iGPU مشترك, 16GB", price: "$700-900", ai: "4B-8B (بطيء)" },
      { category: "Mid-Range", specs: "Ryzen AI 9 / Ultra 7, iGPU مشترك, 32GB", price: "$1,100-1,500", ai: "7B-13B" },
      { category: "High-End GPU", specs: "Ultra 9 / Ryzen 9, RTX 5060/5070 (8-12GB), 32-64GB", price: "$1,600-2,500", ai: "13B-30B" },
      { category: "Extreme Workstation", specs: "Ultra 9 285HX / i9-14900HX, RTX 5090 (24GB), 64-128GB", price: "$3,500-7,000", ai: "30B-70B" },
      { category: "Unified Memory ⭐", specs: "Ryzen AI Max+ 395, Radeon 8060S (حتى 96GB), 128GB موحدة", price: "$3,000-4,000", ai: "70B-120B" },
    ],
    minipc: [
      { category: "Entry (NPU فقط)", specs: "Ryzen 7 255 (38 TOPS), 32GB DDR5", price: "$700-900" },
      { category: "Mid-Range (NPU قوي)", specs: "Ryzen AI 9 HX 370 (80 TOPS), 32GB DDR5", price: "$1,100-1,700" },
      { category: "High-End Unified", specs: "Ryzen AI Max+ 395 (126 TOPS), 128GB موحدة", price: "$2,600-4,000" },
      { category: "Ultra (GPU مخصص)", specs: "i9-14900HX / Ryzen 9, RTX 5070/5090", price: "$1,600-3,500" },
      { category: "Extreme Workstation", specs: "Threadripper / Xeon, RTX PRO 6000", price: "$6,000-12,000" },
    ],
    scenario: {
      name: "Unified Memory (الأفضل للـ AI محلياً)",
      laptop: "HP ZBook Ultra G1a 14 — Ryzen AI Max+ PRO 395, 128GB",
      laptopPrice: "$3,500",
      minipc: "Minisforum MS-S1 Max — Ryzen AI Max+ 395, 128GB, 2TB",
      minipcPrice: "$3,639",
      accessories: "شاشات + Docking + UPS + مايك + كاميرا",
      accessoriesPrice: "$1,958",
      total: "$10,197",
      remaining: "$1,803",
      budget: "$12,000",
    }
  },

  roadmap: [
    { quarter: "Q1", year: 1, title: "التأسيس والانطلاق", tasks: ["تسجيل الكيان القانوني في ماليزيا", "إطلاق بوابة المستثمرين", "اكتساب أول 5 عملاء هندسيين", "تطبيق نظام Error Node الكامل"], milestone: "أول عميل مدفوع" },
    { quarter: "Q2", year: 1, title: "التحقق والتحسين", tasks: ["تحسين Landing Bot بناءً على البيانات", "توثيق 3 دراسات حالة حقيقية", "اختبار 25 هجمة أمنية على بيئة الإنتاج", "تحقيق MRR: SAR 10,000"], milestone: "Product-Market Fit" },
    { quarter: "Q3", year: 1, title: "التوسع الأول", tasks: ["إطلاق رمح الطب (Seen Medical)", "وصول 20 عميل نشط", "توظيف أول موظف دعم فني", "تحقيق MRR: SAR 32,000"], milestone: "20 عميل" },
    { quarter: "Q4", year: 1, title: "النضج والاستقرار", tasks: ["أتمتة كاملة لعمليات التسليم", "بناء فريق دعم مخصص", "مراجعة ربعية شاملة", "تحقيق MRR: SAR 50,000"], milestone: "نقطة التعادل المالي" },
    { quarter: "Y2", year: 2, title: "التوسع الإقليمي", tasks: ["إطلاق رمح القانون والتعليم", "التوسع للسوق الماليزي", "بدء تطوير Micro-SaaS", "MRR: SAR 100,000"], milestone: "40 عميل + رمحين جديدين" },
    { quarter: "Y3", year: 3, title: "القيادة الإقليمية", tasks: ["إطلاق أول منتج Micro-SaaS", "80+ عميل نشط", "قيادة سوق الأتمتة الهندسية", "MRR: SAR 250,000"], milestone: "قيادة إقليمية" },
  ],

  pitchSlides: [
    { title: "الغلاف", content: "Seen Automation AI Agency\nAutomate. Elevate. Halal.\nأول وكالة أتمتة AI حلال في العالم العربي", subtitle: "بوابة الهندسة" },
    { title: "المشكلة", content: "7.6 ساعة/أسبوع مهدرة = 44 يوم عمل/سنة\n67.6% من الرسومات فيها أخطاء\n30-50% من RFIs سببها أخطاء التصميم\nSAR 15,000-45,000 تكلفة مهندس/شهر", subtitle: "نزيف الوقت والجودة" },
    { title: "الحل", content: "AI-Powered Backend Pipelines\nAutomated Reporting (QOO, IR, NCR)\nRFI Management + Financial Automation\nZero-Friction Communication (WhatsApp/Email)\nError Node System (إشعار فوري للطرفين)", subtitle: "مبني على خبرة مهندس ميكانيكي" },
    { title: "لماذا الآن؟", content: "Vision 2030: مشاريع عملاقة (NEOM, Qiddiya)\n+56.25% زيادة الإنفاق الحكومي على AI\n48% AI Adoption في القطاع الخاص السعودي\nCAGR 14.9-28.4%", subtitle: "الفرصة التاريخية" },
    { title: "حجم السوق", content: "TAM (KSA): SAR 13.1-19.5B\nSAM (Engineering): SAR 1.95-2.93B\nSOM (Year 1): SAR 240K-320K\nTAM (Malaysia): $152M-$462M", subtitle: "سوق نمو انفجاري" },
    { title: "نموذج العمل", content: "Starter: SAR 600-1,000/شهر\nGrowth: SAR 1,200-2,000/شهر\nEnterprise: SAR 3,000-5,000/شهر\nHosting: SAR 300-800/شهر\nالشهري = 15-20% من التأسيس", subtitle: "هامش ربح 70-80%" },
    { title: "الجاهزية", content: "✅ 49 ملف استراتيجي مكتمل\n✅ 25 هجمة أمنية في البروتوكول\n✅ 100 سؤال هلوسة مُختبر\n✅ Landing Page تفاعلية + بوت ذكي\n✅ عتاد فيزيائي محدد ($12K)", subtitle: "ليس فكرة — مؤسسة جاهزة" },
    { title: "المنافسون", content: "UiPath: SAR 10K-50K | جزئي | ❌\nPROVEN: SAR 75K+ | لا | ❌\nHivekind: $50-99/س | لا | ❌\nSeen: SAR 600-5K | ✅ هندسي | ✅ حلال", subtitle: "الفجوة الذهبية" },
    { title: "الميزة التنافسية", content: "🕌 حلال 100% (مضاربة شرعية)\n🎯 تخصص هندسي عميق\n💬 Zero-Friction (داخل WhatsApp/Email)\n⚡ SLA 5-30 دقيقة (96x أسرع)\n🔔 Error Node System\n🖥️ Container معزول لكل عميل", subtitle: "لا منافس مباشر" },
    { title: "استراتيجية الدخول", content: "Landing Visit → Bot Analysis → Custom Plan\n→ Confirmation Call (15-20 دقيقة) → Close\nClose Rate: 25-35% (مقابل 10-15% تقليدي)\nSales Cycle: 3-7 أيام (مقابل 2-4 أسابيع)", subtitle: "نموذج ثوري" },
    { title: "الفريق", content: "عمر محمد جميل باعبدالله\nمهندس ميكانيكي (SEGi University)\nخبرة في SABIC وتحسين العمليات\nأحمد: الشريك القانوني (ماليزيا)\nد.سين: مدير العمليات الآلي", subtitle: "خبرة هندسية + تقنية" },
    { title: "المالية", content: "Y1: SAR 240K-320K | 20 عميل | MRR 32K\nY2: SAR 500K-700K | 40 عميل | MRR 100K\nY3: SAR 900K-1.2M | 80 عميل | MRR 250K\nLTV:CAC: 19.3x | Margin: 70-80%", subtitle: "نمو مستدام" },
    { title: "الطلب", content: "SAR 82,500 ($22,000)\nمضاربة شرعية (AAOIFI)\n15% حتى استرداد رأس المال\n15% لمدة 36 شهر بعد ذلك\nBuyout: بعد 24 شهر × 1.5\nMax Duration: 15 سنة", subtitle: "هيكل عادل وشفاف" },
    { title: "التواصل والرؤية", content: "hello@seen-agency.com\nseen-agency.com\nالرؤية Y5: 200+ عميل | $2M+ ARR\nقيادة إقليمية | Micro-SaaS | 10 لغات", subtitle: "Automate. Elevate. Halal." },
  ],

  businessPlan: [
    { title: "الملخص التنفيذي", content: "Seen Automation هي وكالة أتمتة ذكاء اصطناعي حلال 100%، تبدأ بقطاع الهندسة كبوابة ذهبية للدخول إلى السوق، ثم تتوسع لتشمل الطب والقانون والتعليم والتجارة. نعمل بنموذج Zero-Friction الذي يدمج الأتمتة داخل أدوات العميل الحالية (WhatsApp, Email, Slack) دون الحاجة لتعلم برامج جديدة. نطلب تمويلاً بمقدار SAR 82,500 ($22,000) عبر هيكل مضاربة شرعي متوافق مع معايير AAOIFI، لتحقيق إيرادات متكررة بنموذج تسعير يعتمد على 15-20% من قيمة التأسيس شهرياً، مع هامش ربح مستهدف 70-80%." },
    { title: "وصف الشركة", content: "الكيان القانوني: Malaysian Sdn Bhd (قيد التأسيس). المقر التشغيلي: Online / Worldwide. المؤسس التشغيلي: عمر محمد جميل باعبدالله (مهندس ميكانيكي). الشريك القانوني: أحمد (ماليزي). الرؤية: قيادة سوق أتمتة الذكاء الاصطناعي في العالم العربي عبر حلول مرئية مستقلة، حلال 100%. الرسالة: تحرير الطاقات البشرية من الروتين عبر أتمتة ذكية، حلال، ومنخفضة التكلفة. الاستراتيجية ثلاثية المراحل: (1) الهندسة كبوابة ذهبية، (2) التوسع لجميع القطاعات، (3) Productization إلى Micro-SaaS." },
    { title: "تحليل السوق", content: "السوق السعودي: TAM $42.4M-$223M | SAM $15M-$78M | SOM Y1 SAR 240K-320K. السوق الماليزي: TAM $152M-$462M | SAM $53M-$162M. معدل النمو CAGR: 14.9-28.4% (السعودية)، 4.8-7.3% (ماليزيا). محركات النمو: رؤية 2030، التحول الرقمي الحكومي، +56.25% زيادة الإنفاق على AI. الفجوة السوقية: 3 شركات فقط في السعودية تخدم القطاع الهندسي، وصفر في ماليزيا بشكل متخصص. Seen Automation هي الخيار الوحيد المتخصص في العمليات الهندسية الشاملة + حلال + سعر معقول." },
    { title: "تحليل المنافسين", content: "10 منافسين رئيسيين تم تحليلهم. UiPath: SAR 10K-50K، جزئي، غير حلال، معقد. PROVEN Consult: SAR 75K+، لا تخصص، أسعار مرتفعة. Hivekind: $50-99/ساعة، لا تخصص هندسي. Calq: مجاني-مدفوع، نطاق ضيق (BIM فقط). AIQ: SAR 8,812/مستخدم، طاقة فقط. الميزة التنافسية لـ Seen: سعر أقل 10x من المنافسين الرئيسيين، تخصص هندسي عميق، امتثال شرعي 100%، SLA 5-30 دقيقة (96x أسرع من المتوسط)، نظام Error Node للإشعار الفوري." },
    { title: "المنتج والخدمات", content: "4 باقات خدمة: Starter (SAR 600-1,000/شهر، Workflow واحد، SLA 30 دقيقة)، Growth (SAR 1,200-2,000/شهر، 3 Workflows، لوحة تحكم، SLA 15 دقيقة)، Enterprise (SAR 3,000-5,000/شهر، 10+ Workflows، Self-Hosted، SLA 5 دقائق)، Lead-Gen (SAR 300-600/شهر، لا نرفض بسبب الميزانية، مقابل 3 إحالات/سنة). كل باقة تشمل: Error Node System، Container معزول، تشفير AES-256 + TLS 1.3، 25 هجمة أمنية قبل التسليم، 100 سؤال هلوسة. خدمة استضافة إضافية: SAR 300-800/شهر (Container معزول لكل عميل)." },
    { title: "التسويق والمبيعات", content: "استراتيجية الدخول: Landing Bot ذكي (7 أسئلة هندسية) → تقرير مخصص فوري → Confirmation Call (15-20 دقيقة) → إغلاق الصفقة. لا Cold Calls. القنوات: Landing Page + Bot (60%)، LinkedIn Content (20%)، Social Media (15%)، Referrals (5%). Close Rate المستهدف: 25-35% (مقابل 10-15% للنموذج التقليدي). Sales Cycle: 3-7 أيام (مقابل 2-4 أسابيع). Funnel Y1: 5,000 زائر → 1,500 تحليل → 400 Confirmation Call → 20-25 عميل." },
    { title: "العمليات والتسليم", content: "دورة تسليم من 2-4 أسابيع: Discovery (3-5 أيام) → Design (2-3 أيام) → Build (5-10 أيام) → Validation (2-3 أيام، تشمل 25 هجمة أمنية + 100 سؤال هلوسة) → Release (1-2 يوم) → Operate (مستمر). مبدأ Search-Before-Build: لا نبني من الصفر، نبحث عن حلول جاهزة ونخصصها (توفير 60-80% من الوقت). مكتبة SOPs تحتوي على 26 إجراء تشغيلي موحد. نظام Quality Gates: Gate A (Discovery) → Gate B (Design Sign-off) → Gate C (Release Approval) → Gate D (Operational Acceptance)." },
    { title: "الفريق", content: "عمر محمد جميل باعبدالله — المؤسس التشغيلي ومعمار الأنظمة. مهندس ميكانيكي خريج SEGi University في ماليزيا، بخبرة ميدانية في SABIC. متخصص في تحسين العمليات الصناعية وسلاسل الإمداد. أحمد — الشريك القانوني (ماليزي)، مسؤول عن التأسيس القانوني والامتثال والعقود. د.سين — مدير العمليات الآلي، يعمل 24/7 على إدارة العمليات اليومية، مراقبة الأنظمة، ودعم العملاء." },
    { title: "النموذج المالي", content: "ARPU: SAR 1,600/شهر. Churn: 6%. CAC: SAR 1,500. Margin: 70%. Fixed Costs: SAR 3,500/شهر. LTV: SAR 29,000. LTV:CAC: 19.3x. استرداد CAC: 0.6 شهر. نقطة التعادل: الشهر 2. MRR الشهر 12: SAR 32,000. MRR الشهر 36: SAR 67,000. توزيع استخدام الأموال: 60% عمليات وتوظيف (SAR 49,500)، 40% تسويق واستحواذ (SAR 33,000)." },
    { title: "المخاطر والتخفيف", content: "10 مخاطر رئيسية موثقة مع خطط تخفيف مفصلة. أعلى المخاطر: تأخر اعتماد العميل (عالي/متوسط)، منافسة أسعار قوية (عالي/متوسط). أدنى المخاطر: تسرب بيانات العملاء (منخفض/عالي) بسبب التشفير والعزل. جميع المخاطر مغطاة ببروتوكول أمني شامل يتضمن: 25 هجمة محاكاة، 100 سؤال هلوسة، تشفير AES-256، Container Isolation، Error Node System، ومراجعة قانونية ربع سنوية." },
  ],
};