export const DATA = {
  company: {
    name_ar: "سين أوتوميشن",
    name_en: "Seen Automation",
    tagline_ar: "أتمتة. ارتقاء. حلال.",
    tagline_en: "Automate. Elevate. Halal.",
    vision_ar: "قيادة سوق أتمتة الذكاء الاصطناعي في العالم العربي عبر حلول مرئية مستقلة، حلال 100%.",
    vision_en: "Leading the AI automation market in the Arab world through independent, 100% Halal visual solutions.",
    mission_ar: "تحرير الطاقات البشرية من الروتين عبر أتمتة ذكية، حلال، ومنخفضة التكلفة.",
    mission_en: "Liberating human potential from routine through intelligent, Halal, cost-effective automation.",
    founder: {
      name: "عمر محمد جميل باعبدالله",
      name_en: "Omar Mohammed Jamil Baabdullah",
      role_ar: "المؤسس التشغيلي ومعمار الأنظمة",
      role_en: "Operational Founder & Systems Architect",
      bio_ar: "مهندس ميكانيكي خريج SEGi University في ماليزيا، بخبرة ميدانية في SABIC. متخصص في تحسين العمليات الصناعية وسلاسل الإمداد.",
      bio_en: "Mechanical engineer, SEGi University graduate, with SABIC field experience. Specialized in industrial process optimization and supply chains.",
    },
    entity: "Malaysian Sdn Bhd",
    hq_ar: "أونلاين / عالمي",
    hq_en: "Online / Worldwide",
  },
  ask: {
    amount: 82500,
    amount_usd: 22000,
    structure_ar: "مضاربة شرعية (AAOIFI)",
    structure_en: "Sharia-compliant Mudarabah (AAOIFI)",
    phase1: 15,
    phase2: 15,
    phase2_months: 36,
    buyout_months: 24,
    buyout_multiple: 1.5,
    max_years: 15,
  },
  market: {
    tam: { value: 3.5, unit: "B", label_ar: "السوق الكلي", label_en: "Total Addressable Market" },
    sam: { value: 1.95, unit: "B", label_ar: "السوق القابل للخدمة", label_en: "Serviceable Available Market" },
    som: { value: 320, unit: "K", label_ar: "السوق القابل للاستحواذ (Y1)", label_en: "Serviceable Obtainable (Y1)" },
  },
  kpis: [
    { label_ar: "الإيراد الشهري Y1", label_en: "MRR Y1", value: "32K", unit: "SAR", color: "emerald" },
    { label_ar: "الإيراد الشهري Y3", label_en: "MRR Y3", value: "78K", unit: "SAR", color: "gold" },
    { label_ar: "LTV:CAC", label_en: "LTV:CAC", value: "19.3x", unit: "", color: "accent" },
    { label_ar: "نقطة التعادل", label_en: "Break-even", value: "2", unit: "شهر", color: "emerald" },
    { label_ar: "عملاء Y1", label_en: "Customers Y1", value: "20", unit: "", color: "gold" },
    { label_ar: "عملاء Y3", label_en: "Customers Y3", value: "50", unit: "", color: "accent" },
  ],
  financials: {
    arpu: 1600,
    churn: 6,
    cac: 1500,
    margin: 70,
    fixedCosts: 3500,
    newCustomers: 2.3,
    useOfFunds: {
      total: 22000,
      currency: "USD",
      breakdown: [
        {
          category_ar: "العتاد والأجهزة (CapEx)",
          category_en: "Hardware & Equipment",
          percentage: 45,
          amount: 10000,
          description_ar: "سيرفرات محلية، أجهزة اختبار، لابتوب HP ZBook Ultra، Mini PC Minisforum، شاشات، UPS.",
          description_en: "Local servers, testing equipment, HP ZBook Ultra laptop, Minisforum Mini PC, displays, UPS.",
          icon: "💻"
        },
        {
          category_ar: "البنية السحابية",
          category_en: "Cloud Infrastructure",
          percentage: 11,
          amount: 2500,
          description_ar: "Supabase Pro، n8n Cloud، Vercel Pro، Doppler Secrets، Storage للنسخ الاحتياطي.",
          description_en: "Supabase Pro, n8n Cloud, Vercel Pro, Doppler Secrets, backup storage.",
          icon: "☁️"
        },
        {
          category_ar: "ذكاء اصطناعي وAPIs",
          category_en: "AI Models & APIs",
          percentage: 9,
          amount: 2000,
          description_ar: "اشتراكات Qwen، DeepSeek، OpenAI backup، خدمات LLM إضافية لمدة 12 شهر.",
          description_en: "Qwen, DeepSeek, OpenAI backup subscriptions, additional LLM services for 12 months.",
          icon: "🤖"
        },
        {
          category_ar: "التسويق والاستحواذ",
          category_en: "Marketing & Acquisition",
          percentage: 14,
          amount: 3000,
          description_ar: "حملات LinkedIn مستهدفة للقطاع الهندسي، محتوى عالي الجودة، تحسين SEO، Landing Page.",
          description_en: "Targeted LinkedIn campaigns for engineering sector, high-quality content, SEO, Landing Page.",
          icon: "📣"
        },
        {
          category_ar: "قانوني وامتثال",
          category_en: "Legal & Compliance",
          percentage: 7,
          amount: 1500,
          description_ar: "تسجيل الكيان الماليزي، مراجعة شرعية للعقود، NDA/MSA/SOW templates.",
          description_en: "Malaysian entity registration, Sharia contract review, NDA/MSA/SOW templates.",
          icon: "⚖️"
        },
        {
          category_ar: "أدوات برمجية",
          category_en: "Tools & Software",
          percentage: 5,
          amount: 1000,
          description_ar: "JetBrains، Figma، Notion Team، Looker Studio Pro، أدوات التطوير.",
          description_en: "JetBrains, Figma, Notion Team, Looker Studio Pro, development tools.",
          icon: "🛠️"
        },
        {
          category_ar: "احتياطي طوارئ",
          category_en: "Contingency Reserve",
          percentage: 5,
          amount: 1000,
          description_ar: "احتياطي للطوارئ غير المتوقعة، صيانة، وتكاليف إضافية محتملة.",
          description_en: "Reserve for unexpected emergencies, maintenance, and potential additional costs.",
          icon: "🛡️"
        },
        {
          category_ar: "سيولة تشغيلية شهرية",
          category_en: "Monthly OpEx Buffer",
          percentage: 4,
          amount: 1000,
          description_ar: "Buffer للسيولة التشغيلية في الأشهر الأولى قبل تحقيق الإيراد الكافي.",
          description_en: "Operational liquidity buffer for the first months before sufficient revenue.",
          icon: "💵"
        }
      ]
    },
    revenueStreams: [
      { name_ar: "رسوم التأسيس (Setup)", name_en: "Setup Fees", percentage: 35, amount: 134400, color: "#0F5132" },
      { name_ar: "اشتراكات شهرية", name_en: "Monthly Retainers", percentage: 45, amount: 172800, color: "#D4AF37" },
      { name_ar: "استضافة ومدد", name_en: "Hosting & Retainers", percentage: 12, amount: 46080, color: "#F97316" },
      { name_ar: "تطوير مخصص", name_en: "Custom Development", percentage: 8, amount: 30720, color: "#B8962E" }
    ],
    scenarios: [
      { 
        name_ar: "متحفظ", name_en: "Conservative",
        clients_y1: 12, clients_y3: 30, 
        mrr_y1: 19200, mrr_y3: 48000,
        revenue_y1: 230400, revenue_y3: 576000,
        probability: 25
      },
      { 
        name_ar: "أساسي (المتوقع)", name_en: "Base (Expected)",
        clients_y1: 20, clients_y3: 50, 
        mrr_y1: 32000, mrr_y3: 80000,
        revenue_y1: 384000, revenue_y3: 960000,
        probability: 50
      },
      { 
        name_ar: "متفائل", name_en: "Optimistic",
        clients_y1: 30, clients_y3: 80, 
        mrr_y1: 48000, mrr_y3: 128000,
        revenue_y1: 576000, revenue_y3: 1536000,
        probability: 25
      }
    ],
    cashFlow: [
      { month: 1, revenue: 0, costs: 8500, profit: -8500, cumulative: -8500 },
      { month: 2, revenue: 8000, costs: 7000, profit: 1000, cumulative: -7500 },
      { month: 3, revenue: 16000, costs: 7500, profit: 8500, cumulative: 1000 },
      { month: 4, revenue: 22000, costs: 8000, profit: 14000, cumulative: 15000 },
      { month: 5, revenue: 26000, costs: 8500, profit: 17500, cumulative: 32500 },
      { month: 6, revenue: 29000, costs: 9000, profit: 20000, cumulative: 52500 },
      { month: 7, revenue: 32000, costs: 9500, profit: 22500, cumulative: 75000 },
      { month: 8, revenue: 34000, costs: 10000, profit: 24000, cumulative: 99000 },
      { month: 9, revenue: 36000, costs: 10500, profit: 25500, cumulative: 124500 },
      { month: 10, revenue: 38000, costs: 11000, profit: 27000, cumulative: 151500 },
      { month: 11, revenue: 40000, costs: 11500, profit: 28500, cumulative: 180000 },
      { month: 12, revenue: 43000, costs: 12000, profit: 31000, cumulative: 211000 }
    ],
    unitEconomics: [
      { metric_ar: "متوسط سعر التأسيس", metric_en: "Average Setup Fee", value: "SAR 6,720", color: "emerald" },
      { metric_ar: "ARPU الشهري", metric_en: "Monthly ARPU", value: "SAR 1,600", color: "gold" },
      { metric_ar: "تكلفة الاكتساب (CAC)", metric_en: "CAC", value: "SAR 1,500", color: "accent" },
      { metric_ar: "عمر العميل المتوقع", metric_en: "Expected Customer Lifetime", value: "18 شهر", color: "emerald" },
      { metric_ar: "القيمة الدائمة (LTV)", metric_en: "LTV", value: "SAR 29,000", color: "gold" },
      { metric_ar: "نسبة LTV:CAC", metric_en: "LTV:CAC Ratio", value: "19.3x", color: "accent" },
      { metric_ar: "فترة استرداد CAC", metric_en: "CAC Payback", value: "0.9 شهر", color: "emerald" },
      { metric_ar: "نسبة التسرب الشهرية", metric_en: "Monthly Churn", value: "6%", color: "red" },
      { metric_ar: "هامش الربح الإجمالي", metric_en: "Gross Margin", value: "70%", color: "gold" },
      { metric_ar: "صافي هامش الربح", metric_en: "Net Profit Margin", value: "45%", color: "accent" }
    ],
    breakEven: {
      month: 2,
      fixed_costs: 3500,
      contribution_margin: 1120,
      description_ar: "نقطة التعادل التشغيلية تُحقق في الشهر الثاني، حيث يتجاوز الإيراد المتكرر التكاليف الثابتة الشهرية البالغة SAR 3,500. هذا ممكن بفضل هامش الربح الإجمالي 70% الذي يتيح تغطية سريعة للتكاليف.",
      description_en: "Operational break-even is achieved in month 2, where recurring revenue exceeds fixed monthly costs of SAR 3,500. This is possible thanks to the 70% gross margin enabling rapid cost coverage."
    },
    projections: {
      y1: { revenue: 384000, costs: 106800, profit: 277200 },
      y2: { revenue: 600000, costs: 144000, profit: 456000 },
      y3: { revenue: 936000, costs: 195000, profit: 741000 },
    },

  },
  packages: [
    { name: "Starter", setup_min: 3000, setup_max: 5000, monthly_min: 600, monthly_max: 1000, sla: "30 دقيقة", workflows: 1, features: ["Workflow واحد", "قناة واحدة", "تقرير شهري", "Error Node أساسي"] },
    { name: "Growth", setup_min: 6000, setup_max: 10000, monthly_min: 1200, monthly_max: 2000, sla: "15 دقيقة", workflows: 3, features: ["3 Workflows", "قنوات متعددة", "لوحة تحكم", "تكامل API", "SLA موثق"] },
    { name: "Enterprise", setup_min: 15000, setup_max: 25000, monthly_min: 3000, monthly_max: 5000, sla: "5 دقائق", workflows: 10, features: ["10+ Workflows", "Self-Hosted", "دعم VIP", "مدير حساب", "SLA 99.5%"] },
    { name: "Lead-Gen", setup_min: 1000, setup_max: 3000, monthly_min: 300, monthly_max: 600, sla: "30 دقيقة", workflows: 1, features: ["Workflow بسيط", "3 إحالات/سنة", "لا نرفض بسبب الميزانية"] },
  ],
  competitors: [
    { name: "UiPath", price: "SAR 10K-50K", specialty_ar: "جزئي", halal: false, weakness_ar: "معقد + مكلف" },
    { name: "PROVEN", price: "SAR 75K+", specialty_ar: "لا", halal: false, weakness_ar: "أسعار مرتفعة" },
    { name: "Hivekind", price: "$50-99/hr", specialty_ar: "لا", halal: false, weakness_ar: "لا تخصص هندسي" },
    { name: "Seen", price: "SAR 600-5K", specialty_ar: "هندسي ✅", halal: true, weakness_ar: "—" },
  ],
  sectors: [
    {
      id: "eng",
      name_ar: "الهندسة",
      name_en: "Engineering",
      status: "active",
      icon: "🏗️",
      desc_ar: "أتمتة RFIs، QOO، Submittals، تقارير التقدم، وتنسيق التخصصات للمكاتب الهندسية.",
      desc_en: "Automating RFIs, QOO, submittals, progress reporting, and discipline coordination for engineering firms.",
      timeline: "Q4 2026",
      target_clients: 20,
      justification_ar: "خلفية المؤسس الهندسية في SABIC تمنحنا فهماً مباشراً للاختناقات التشغيلية. الرقمنة وأتمتة مراجعة RFIs يمكن أن تخفض زمن المعالجة اليدوي بشكل كبير، وجزء مهم من RFIs ينشأ من أخطاء تصميم أو نقص تنسيق.",
      justification_en: "The founder's engineering background at SABIC gives direct insight into operational bottlenecks. Digitization and automated RFI review can substantially reduce manual processing time, while a significant share of RFIs originate from design errors or coordination gaps.",
      subSectors_ar: ["الميكانيكا والكهرباء والسباكة (MEP)", "الهندسة المدنية", "المعمارية", "الإشراف الهندسي", "إدارة المشاريع الهندسية"],
      subSectors_en: ["Mechanical, Electrical, Plumbing (MEP)", "Civil Engineering", "Architecture", "Engineering Supervision", "Engineering Project Management"],
      persona: {
        role_ar: "مدير مكتب هندسي استشاري",
        role_en: "Consulting Engineering Office Manager",
        pain_ar: "ضياع ساعات أسبوعياً في متابعة RFIs، تجميع القوائم، إعداد التقارير، وتنسيق المراسلات بين التخصصات.",
        pain_en: "Losing hours weekly tracking RFIs, compiling schedules, preparing reports, and coordinating correspondence across disciplines.",
        solution_ar: "خطوط أتمتة تعمل داخل القنوات اليومية مثل البريد وواتساب، مع إشعار فوري عند أي خطأ أو تأخير.",
        solution_en: "Automation pipelines operating inside daily channels such as email and WhatsApp, with instant alerts for any error or delay.",
      },
      readiness: { workflows: 12, sops: 26, percentage: 85 },
    },
    {
      id: "med",
      name_ar: "الطب",
      name_en: "Medical",
      status: "upcoming",
      icon: "🏥",
      desc_ar: "أتمتة السجلات الطبية، التقارير السريرية، المواعيد، والمتابعات الإدارية للعيادات والمراكز الطبية.",
      desc_en: "Automating medical records, clinical reports, appointments, and administrative follow-ups for clinics and medical centers.",
      timeline: "Q2 2027",
      target_clients: 10,
      justification_ar: "القطاع الطبي يعاني من عبء إداري مرتفع، والعيادات الصغيرة تحتاج حلاً منخفض الاحتكاك دون فرض أنظمة ثقيلة على الطاقم الطبي.",
      justification_en: "The medical sector carries a heavy administrative burden, and small clinics need a low-friction solution without imposing heavyweight systems on medical staff.",
      subSectors_ar: ["العيادات الخاصة", "المختبرات", "الصيدليات", "مراكز التأهيل", "الرعاية المنزلية"],
      subSectors_en: ["Private Clinics", "Laboratories", "Pharmacies", "Rehabilitation Centers", "Home Care"],
      persona: {
        role_ar: "مالك عيادة خاصة",
        role_en: "Private Clinic Owner",
        pain_ar: "وقت ضائع في الإدخال اليدوي، متابعة المرضى، وإعداد التقارير بدل التركيز على الخدمة السريرية.",
        pain_en: "Time lost to manual entry, patient follow-up, and report preparation instead of clinical service.",
        solution_ar: "أتمتة التذكيرات، التقارير، واستلام الطلبات عبر قنوات مألوفة مع ضوابط خصوصية.",
        solution_en: "Automated reminders, reports, and intake through familiar channels with privacy controls.",
      },
      readiness: { workflows: 5, sops: 12, percentage: 45 },
    },
    {
      id: "leg",
      name_ar: "القانون",
      name_en: "Legal",
      status: "upcoming",
      icon: "⚖️",
      desc_ar: "مراجعة العقود، استخراج البنود، توحيد الصياغة، ومتابعة المواعيد القانونية.",
      desc_en: "Contract review, clause extraction, drafting standardization, and legal deadline tracking.",
      timeline: "Q3 2027",
      target_clients: 8,
      justification_ar: "المكاتب القانونية تصرف ساعات طويلة في مراجعة مستندات متشابهة، وهو نشاط قابل للأتمتة الآمنة إذا ضبطنا نطاق المراجعة الإنسانية.",
      justification_en: "Law firms spend long hours reviewing similar documents, a task suitable for safe automation when human review scope is properly controlled.",
      subSectors_ar: ["المحاماة التجارية", "العقود", "الامتثال", "التوثيق", "فض المنازعات"],
      subSectors_en: ["Commercial Law", "Contracts", "Compliance", "Documentation", "Dispute Resolution"],
      persona: {
        role_ar: "شريك في مكتب محاماة",
        role_en: "Law Firm Partner",
        pain_ar: "مراجعة يدوية متكررة للعقود وتوحيد المصطلحات عبر ملفات كثيرة.",
        pain_en: "Repeated manual contract review and terminology consistency across many files.",
        solution_ar: "مساعد أتمتة يستخرج البنود وينبه للمخاطر قبل المراجعة البشرية النهائية.",
        solution_en: "An automation assistant that extracts clauses and flags risks before final human review.",
      },
      readiness: { workflows: 3, sops: 8, percentage: 30 },
    },
    {
      id: "edu",
      name_ar: "التعليم",
      name_en: "Education",
      status: "upcoming",
      icon: "🎓",
      desc_ar: "أتمتة العمليات الإدارية، تقييم الطلاب، الحضور، والتقارير الدورية.",
      desc_en: "Automating administrative operations, student assessment, attendance, and periodic reporting.",
      timeline: "Q4 2027",
      target_clients: 12,
      justification_ar: "المؤسسات التعليمية الخاصة تحتاج تحسين الكفاءة الإدارية دون تعقيد على المعلم أو الطالب.",
      justification_en: "Private educational institutions need administrative efficiency without adding complexity for teachers or students.",
      subSectors_ar: ["المدارس الخاصة", "الجامعات", "مراكز التدريب", "التعليم الإلكتروني"],
      subSectors_en: ["Private Schools", "Universities", "Training Centers", "E-Learning"],
      persona: {
        role_ar: "مدير مدرسة خاصة",
        role_en: "Private School Principal",
        pain_ar: "تشتت البيانات بين أوراق، جداول، وبريد إلكتروني، مع تقارير يدوية مرهقة.",
        pain_en: "Data scattered across papers, schedules, and email, with exhausting manual reporting.",
        solution_ar: "توحيد التنبيهات والتقارير عبر خطوط أتمتة بسيطة.",
        solution_en: "Unifying alerts and reports through simple automation pipelines.",
      },
      readiness: { workflows: 4, sops: 10, percentage: 35 },
    },
    {
      id: "com",
      name_ar: "التجارة",
      name_en: "Commerce",
      status: "upcoming",
      icon: "🛒",
      desc_ar: "أتمتة الفوترة الإلكترونية، المخزون، أوامر الشراء، ومتابعة الموردين.",
      desc_en: "Automating e-invoicing, inventory, purchase orders, and supplier follow-up.",
      timeline: "Q1 2028",
      target_clients: 15,
      justification_ar: "متطلبات الفوترة الإلكترونية في السعودية تخلق حاجة واضحة لحلول امتثال التشغيل الآلي لدى المنشآت الصغيرة والمتوسطة.",
      justification_en: "Saudi e-invoicing requirements create clear demand for compliant operational automation among small and medium businesses.",
      subSectors_ar: ["التجارة الإلكترونية", "التجزئة", "التوزيع", "اللوجستيات"],
      subSectors_en: ["E-commerce", "Retail", "Distribution", "Logistics"],
      persona: {
        role_ar: "مالك متجر إلكتروني أو توزيع",
        role_en: "E-commerce or Distribution Owner",
        pain_ar: "إدارة الفواتير والمخزون ومتابعة الموردين يدوياً مع مخاطر امتثال.",
        pain_en: "Manual invoice, inventory, and supplier management with compliance risk.",
        solution_ar: "أتمتة الفوترة والتنبيهات وتقارير المخزون.",
        solution_en: "Automated invoicing, alerts, and inventory reporting.",
      },
      readiness: { workflows: 6, sops: 14, percentage: 50 },
    },
  ],
  risks: [
    { name_ar: "تأخر اعتماد العميل على الحل", name_en: "Client adoption delay", category_ar: "تشغيلية", category_en: "Operational", prob: "high", impact: "high", mitigation_ar: "بدء تجريبي محدود، تدريب قصير، ولوحة واضحة للقيمة الأسبوعية.", mitigation_en: "Limited pilot, short training, and a clear weekly value dashboard." },
    { name_ar: "تغير نطاق المشروع أثناء التنفيذ", name_en: "Scope creep during delivery", category_ar: "تشغيلية", category_en: "Operational", prob: "high", impact: "medium", mitigation_ar: "نموذج Change Request رسمي مع تسعير وزمن منفصل.", mitigation_en: "Formal Change Request model with separate pricing and timeline." },
    { name_ar: "فشل تكامل API خارجي", name_en: "External API failure", category_ar: "تقنية", category_en: "Technical", prob: "medium", impact: "high", mitigation_ar: "آليات تراجع، Error Node، ومراقبة يومية.", mitigation_en: "Fallback mechanisms, Error Node, and daily monitoring." },
    { name_ar: "اعتماد على مزود نموذج ذكاء اصطناعي واحد", name_en: "Dependence on a single AI model provider", category_ar: "تقنية", category_en: "Technical", prob: "medium", impact: "high", mitigation_ar: "تصميم متعدد النماذج: Qwen، DeepSeek، وبدائل محلية عند الحاجة.", mitigation_en: "Multi-model design: Qwen, DeepSeek, and local alternatives when needed." },
    { name_ar: "منافسة أسعار من وكالات عامة", name_en: "Price competition from general agencies", category_ar: "سوقية", category_en: "Market", prob: "high", impact: "medium", mitigation_ar: "التأكيد على التخصص الهندسي، SLA، والـ ROI لا على السعر فقط.", mitigation_en: "Emphasize engineering specialization, SLA, and ROI rather than price alone." },
    { name_ar: "بطء دورة قرار المستثمر أو العميل", name_en: "Slow investor or client decision cycle", category_ar: "سوقية", category_en: "Market", prob: "medium", impact: "medium", mitigation_ar: "حقيبة مستثمر جاهزة، متابعة آلية، ونموذج تجريبي منخفض المخاطر.", mitigation_en: "Investor-ready briefcase, automated follow-up, and low-risk pilot model." },
    { name_ar: "تغير تنظيمي في حماية البيانات أو الفوترة", name_en: "Regulatory change in data protection or e-invoicing", category_ar: "تنظيمية", category_en: "Regulatory", prob: "medium", impact: "high", mitigation_ar: "مراجعة ربع سنوية، DPA، وتصميم قابل للتعديل.", mitigation_en: "Quarterly review, DPA, and adaptable design." },
    { name_ar: "مخاطر امتثال شرعي في العقود", name_en: "Sharia compliance risk in contracts", category_ar: "قانونية", category_en: "Legal", prob: "low", impact: "high", mitigation_ar: "عقد مضاربة متوافق مع AAOIFI ومراجعة شرعية قبل التوقيع.", mitigation_en: "AAOIFI-aligned Mudarabah contract and Sharia review before signing." },
    { name_ar: "نقص سيولة تشغيلية قبل الإيرادات", name_en: "Pre-revenue liquidity shortfall", category_ar: "مالية", category_en: "Financial", prob: "medium", impact: "high", mitigation_ar: "التركيز على CapEx وR&D فقط، وتأجيل أي تكاليف غير منتجة.", mitigation_en: "Focus only on CapEx and R&D, deferring non-productive costs." },
    { name_ar: "خطأ في مخرجات الذكاء الاصطناعي يؤثر على العميل", name_en: "AI output error affecting client", category_ar: "جودة", category_en: "Quality", prob: "medium", impact: "high", mitigation_ar: "100 سؤال هلوسة، مراجعة بشرية للمخرجات الحرجة، وError Node.", mitigation_en: "100 hallucination tests, human review for critical outputs, and Error Node." },
    { name_ar: "تسرب معرفة تشغيلية بسبب الاعتماد على شخص واحد", name_en: "Knowledge leakage due to single-person dependency", category_ar: "تنظيمية", category_en: "Organizational", prob: "high", impact: "medium", mitigation_ar: "توثيق SOPs، سجل قرارات، وأتمتة العمليات الروتينية.", mitigation_en: "SOP documentation, decision log, and automation of routine operations." },
    { name_ar: "خلل أمني في بيانات العميل", name_en: "Client data security incident", category_ar: "أمنية", category_en: "Security", prob: "low", impact: "high", mitigation_ar: "عزل الحاويات، تشفير AES-256 وTLS 1.3، ومحاكاة 25 هجمة.", mitigation_en: "Container isolation, AES-256 and TLS 1.3 encryption, and 25-attack simulation." },
  ],
  hardware: {
    laptops: [
      { category: "Entry-Level", specs: "Ryzen AI 7, 16GB", price: "$700-900", ai: "4B-8B" },
      { category: "Mid-Range", specs: "Ryzen AI 9, 32GB", price: "$1,100-1,500", ai: "7B-13B" },
      { category: "High-End", specs: "RTX 5070, 64GB", price: "$1,600-2,500", ai: "13B-30B" },
      { category: "Extreme", specs: "RTX 5090 24GB, 128GB", price: "$3,500-7,000", ai: "30B-70B" },
      { category: "Unified Memory ⭐", specs: "Ryzen AI Max+ 395, 128GB", price: "$3,000-4,000", ai: "70B-120B" },
    ],
    minipc: [
      { category: "Entry", specs: "Ryzen 7, 32GB", price: "$700-900" },
      { category: "Mid-Range", specs: "Ryzen AI 9 HX, 32GB", price: "$1,100-1,700" },
      { category: "High-End", specs: "Ryzen AI Max+, 128GB", price: "$2,600-4,000" },
      { category: "Ultra GPU", specs: "RTX 5070/5090", price: "$1,600-3,500" },
      { category: "Extreme", specs: "RTX PRO 6000", price: "$6,000-12,000" },
    ],
    scenario: {
      name_ar: "Unified Memory",
      name_en: "Unified Memory",
      laptop: "HP ZBook Ultra G1a 14 — Ryzen AI Max+ PRO 395, 128GB",
      laptop_price: 3500,
      minipc: "Minisforum MS-S1 Max — Ryzen AI Max+ 395, 128GB, 2TB",
      minipc_price: 3639,
      accessories: "شاشات + Docking + UPS",
      accessories_en: "Displays + Docking + UPS",
      accessories_price: 1958,
      total: 10197,
      remaining: 1803,
      budget: 12000,
    },
  },
  roadmap: [
    { phase_ar: "💡 لحظة الفكرة والتحقق", phase_en: "Idea & Validation", date_ar: "Q1-Q2 2026", date_en: "Q1-Q2 2026", desc_ar: "دراسة السوق، تحليل المنافسين، وبناء الـ 49 ملفاً الاستراتيجي.", desc_en: "Market study, competitor analysis, and building the 49 strategic files." },
    { phase_ar: "🏛️ التأسيس القانوني والعتاد", phase_en: "Legal & Hardware Setup", date_ar: "Q3 2026", date_en: "Q3 2026", desc_ar: "تسجيل الكيان في ماليزيا، شراء العتاد ($10K)، وإعداد البنية التحتية.", desc_en: "Entity registration in Malaysia, hardware purchase ($10K), and infrastructure setup." },
    { phase_ar: "🚀 الإطلاق التجريبي", phase_en: "Beta Launch", date_ar: "أكتوبر 2026", date_en: "October 2026", desc_ar: "إطلاق بوابة المستثمرين، اختبار Landing Bot، وضبط الأنظمة.", desc_en: "Investor portal launch, Landing Bot testing, and systems tuning." },
    { phase_ar: "⭐ أول عميل مدفوع", phase_en: "First Paid Client", date_ar: "Q4 2026", date_en: "Q4 2026", desc_ar: "إغلاق أول عقد مع مكتب هندسي، وتطبيق كامل لبروتوكول Error Node قبل التسليم.", desc_en: "Close the first paid engineering contract, with full Error Node protocol applied before delivery." },
    { phase_ar: "📈 التوسع الأول", phase_en: "First Expansion", date_ar: "Q1-Q2 2027", date_en: "Q1-Q2 2027", desc_ar: "الوصول إلى 20 عميل، إطلاق رمح الطب، MRR: SAR 32K.", desc_en: "Reach 20 clients, launch the medical spear, MRR: SAR 32K." },
    { phase_ar: "🌍 القيادة الإقليمية", phase_en: "Regional Leadership", date_ar: "2028", date_en: "2028", desc_ar: "80+ عميل، Micro-SaaS، MRR: SAR 250K.", desc_en: "80+ clients, Micro-SaaS, MRR: SAR 250K." },
  ],
  businessPlan: [
    {
      title_ar: "الملخص التنفيذي",
      title_en: "Executive Summary",
      content_ar: "Seen Automation AI Agency وكالة أتمتة ذكاء اصطناعي متخصصة في القطاع الهندسي أولاً، ثم التوسع الأفقي إلى قطاعات أخرى بعد إثبات النموذج.\nنعمل بنموذج Zero-Friction: الأتمتة تعمل داخل الأدوات التي يستخدمها العميل يومياً، دون فرض منصة جديدة أو تدريب معقد.\nالطلب الاستثماري الحالي هو 15,000 دولار، موجه أساساً للعتاد والبحث والتطوير والتسويق، دون رواتب موظفين في هذه المرحلة.\nالميزة الأساسية ليست التقنية فقط، بل الفهم الميداني للاختناقات التشغيلية في المكاتب الهندسية من خلفية المؤسس الهندسية.\nالهدف الأول هو إغلاق أول عميل مدفوع في الربع الرابع من 2026 بعد بناء منتج قابل للتسليم وقياس الأثر.",
      content_en: "Seen Automation AI Agency is an AI automation agency specialized first in engineering, then expanding horizontally to other sectors after proving the model.\nWe operate a Zero-Friction model: automation works inside the client's daily tools, without imposing a new platform or complex training.\nThe current investment ask is USD 15,000, directed mainly to hardware, R&D, and marketing, with no employee salaries at this stage.\nThe core advantage is not technology alone, but field understanding of operational bottlenecks in engineering firms from the founder's engineering background.\nThe first goal is to close the first paid client in Q4 2026 after building a deliverable product and measuring impact.",
    },
    {
      title_ar: "مشكلة السوق",
      title_en: "Market Pain",
      content_ar: "المكاتب الهندسية تفقد ساعات أسبوعية في مهام متكررة: متابعة RFIs، تجميع القوائم، إعداد التقارير، وتنسيق المراسلات.\nجزء مهم من هذه المهام ناتج عن أخطاء تصميم أو نقص تنسيق بين التخصصات، ما يرفع تكلفة التأخير ويعيد العمل.\nالحلول الكبيرة مثل UiPath مناسبة للمؤسسات الضخمة، لكنها معقدة ومكلفة للشركات الصغيرة والمتوسطة.\nالحلول العامة لا تفهم لغة المهندس ولا دورة المستند الهندسي، فتنتج أتمتة شكلية بلا أثر تشغيلي.\nالعميل لا يحتاج برنامجاً جديداً، بل يحتاج إزالة الاحتكاك من العملية الحالية.",
      content_en: "Engineering firms lose weekly hours to repetitive tasks: RFI tracking, schedule compilation, report preparation, and correspondence coordination.\nA significant share of these tasks stems from design errors or poor interdisciplinary coordination, increasing delay cost and rework.\nLarge solutions such as UiPath suit enterprises but are complex and expensive for small and medium firms.\nGeneric solutions do not understand engineering language or document lifecycle, producing superficial automation without operational impact.\nThe client does not need another software; the client needs friction removed from the current process.",
    },
    {
      title_ar: "الحل المقترح",
      title_en: "Proposed Solution",
      content_ar: "نبني خطوط أتمتة خلفية تربط البريد، واتساب، المستندات، وقواعد البيانات دون تغيير عادات المستخدم.\nكل workflow يمر بمراحل: استقبال، تحقق، معالجة، إشعار، وتوثيق.\nنستخدم n8n للتنسيق، Supabase للبيانات، ونماذج ذكاء اصطناعي مثل Qwen وDeepSeek للمعالجة اللغوية والاستخراج.\nError Node هو طبقة حماية ترسل تنبيهاً فورياً عند فشل خطوة أو ظهور مخرج غير متسق.\nالتسليم لا يكون بكود فقط، بل بإجراء تشغيلي موثق ولوحة متابعة بسيطة.",
      content_en: "We build backend automation pipelines connecting email, WhatsApp, documents, and databases without changing user habits.\nEach workflow passes through stages: intake, validation, processing, notification, and documentation.\nWe use n8n for orchestration, Supabase for data, and AI models such as Qwen and DeepSeek for language processing and extraction.\nError Node is a protection layer that sends instant alerts when a step fails or an inconsistent output appears.\nDelivery is not code only; it includes a documented operating procedure and a simple monitoring dashboard.",
    },
    {
      title_ar: "نموذج الإيرادات",
      title_en: "Revenue Model",
      content_ar: "نموذج الإيراد يقوم على رسم تأسيس للمشروع plus اشتراك شهري للصيانة والتطوير.\nالاشتراك الشهري يعادل تقريباً 15 إلى 20 بالمئة من قيمة التأسيس، ما يخلق إيراداً متكرراً قابلاً للتنبؤ.\nباقاتنا أربع: Starter، Growth، Enterprise، وLead-Gen لمن لا يستطيع التحمل الفوري.\nلا نعتمد على بيع ساعات فقط، لأن ذلك يحد من التوسع ويجعل الإيراد هشاً.\nالهدف هو تحويل الخدمة إلى منتج قابل للتكرار، ثم إلى Micro-SaaS بعد نضج النموذج.",
      content_en: "The revenue model is based on a project setup fee plus a monthly maintenance and development subscription.\nThe monthly subscription is approximately 15 to 20 percent of setup value, creating predictable recurring revenue.\nOur packages are four: Starter, Growth, Enterprise, and Lead-Gen for those who cannot afford immediate commitment.\nWe do not rely on hour-based sales only, because that limits scale and makes revenue fragile.\nThe goal is to convert service into a repeatable product, then into Micro-SaaS after the model matures.",
    },
    {
      title_ar: "حجم السوق المستهدف",
      title_en: "Target Market Size",
      content_ar: "السوق السعودي هو البوابة الأولى بسبب رؤية 2030، حجم المشاريع، والحاجة إلى رفع كفاءة القطاع الهندسي.\nالسوق الماليزي هو التوسع الثاني بسبب وجود المؤسس والشريك القانوني وانخفاض المنافسة المتخصصة.\nنقيس TAM/SAM/SOM بحذر، ونعرضها كمجال فرص لا كوعود دخل.\nTAM العام للذكاء الاصطناعي في السعودية كبير ومتنامي حسب تقارير 2025-2026.\nSAM الحقيقي هو شريحة المكاتب الهندسية والشركات الخدمية المتخصصة القادرة على الدفع.\nSOM السنة الأولى مستمد من 20 عميلاً محتملاً بمتوسط ARPU معقول، لا من تضخيم رقمي.",
      content_en: "The Saudi market is the first gateway due to Vision 2030, project volume, and the need to improve engineering-sector efficiency.\nThe Malaysian market is the second expansion due to founder and legal partner presence and lower specialized competition.\nWe measure TAM/SAM/SOM cautiously and present them as opportunity space, not income promises.\nGeneral Saudi AI TAM is large and growing according to 2025-2026 reports.\nThe real SAM is the segment of engineering firms and specialized service companies able to pay.\nYear-one SOM is derived from 20 potential clients at a reasonable ARPU, not digital inflation.",
    },
    {
      title_ar: "الميزة التنافسية",
      title_en: "Competitive Advantage",
      content_ar: "نحن لا ننافس UiPath في Enterprise، ولا ننافس الوكالات العامة في كل القطاعات.\nنتخصص في الهندسة لأن فيها ألماً واضحاً وقدرة دفع أعلى من المستهلك العادي.\nنجمع بين ثلاث مزايا نادراً ما تجتمع: تخصص هندسي، امتثال شرعي، وسرعة SLA.\nالامتثال الشرعي ليس شعاراً تسويقياً، بل هيكل عقد مضاربة ومراجعة شرعية.\nالسرعة ليست وعداً، بل بروتوكول Error Node ومراقبة يومية.",
      content_en: "We do not compete with UiPath in enterprise, nor with general agencies across all sectors.\nWe specialize in engineering because the pain is clear and willingness to pay is higher than ordinary consumers.\nWe combine three rarely combined advantages: engineering specialization, Sharia compliance, and fast SLA.\nSharia compliance is not a marketing slogan; it is a Mudarabah contract structure and Sharia review.\nSpeed is not a promise; it is an Error Node protocol and daily monitoring.",
    },
    {
      title_ar: "استراتيجية الدخول للسوق",
      title_en: "Go-to-Market Strategy",
      content_ar: "الدخول يبدأ بصفحة هبوط تفاعلية تحلل مشكلة الزائر وتنتج تقريراً مبدئياً.\nثم تحويل الاهتمام إلى مكالمة تأكيد قصيرة مدتها 15 إلى 20 دقيقة.\nلا نبيع بالخوف أو الضغط النفسي، بل بالبيانات والتجربة المحدودة.\nأول 5 عملاء هم حالة تأسيس، لا حالة نمو؛ الهدف منهم التعلم وتوثيق SOPs.\nبعد أول 5 عملاء، ننتقل إلى إحالات مدفوعة وشراكات مع مكاتب هندسية صغيرة.",
      content_en: "Entry begins with an interactive landing page that analyzes the visitor problem and produces a preliminary report.\nThen interest is converted into a short confirmation call of 15 to 20 minutes.\nWe do not sell through fear or psychological pressure, but through data and limited trials.\nThe first five clients are foundational cases, not growth cases; the goal is learning and SOP documentation.\nAfter the first five clients, we move to paid referrals and partnerships with small engineering firms.",
    },
    {
      title_ar: "رحلة العميل",
      title_en: "Customer Journey",
      content_ar: "الاكتشاف: يرى العميل مشكلة مألوفة في صفحة الهبوط أو المحتوى.\nالتشخيص: يملأ نموذجاً قصيراً أو يتحدث مع Bot لاستخراج الألم الأساسي.\nالتقرير: يحصل على خطة مبدئية تبين ما يمكن أتمتته وما لا يمكن.\nالاتفاق: نحدد نطاقاً صغيراً قابلاً للتسليم في 2 إلى 4 أسابيع.\nالتسليم: نطلق Workflow مع تدريب خفيف ووثيقة SOP.\nالتشغيل: مراقبة يومية، تقارير شهرية، وتحسين مستمر.",
      content_en: "Discovery: the client sees a familiar problem on the landing page or content.\nDiagnosis: the client completes a short form or speaks with a bot to extract the core pain.\nReport: the client receives a preliminary plan showing what can be automated and what cannot.\nAgreement: we define a small scope deliverable in 2 to 4 weeks.\nDelivery: we launch a workflow with light training and an SOP document.\nOperation: daily monitoring, monthly reports, and continuous improvement.",
    },
    {
      title_ar: "البنية التحتية التقنية",
      title_en: "High-Level Tech Stack",
      content_ar: "n8n لتنسيق خطوط الأتمتة والتكاملات.\nSupabase لقاعدة البيانات، المصادقة، وتخزين الملفات عند الحاجة.\nنماذج ذكاء اصطناعي متعددة لاستخراج النصوص وتلخيصها وتصنيفها.\nطبقة أمان عزل لكل عميل، تشفير أثناء النقل وعند التخزين.\nلا نكشف الكود المصدري أو البرومبتات الداخلية في المواد العامة.",
      content_en: "n8n for orchestrating automation pipelines and integrations.\nSupabase for database, authentication, and file storage when needed.\nMultiple AI models for text extraction, summarization, and classification.\nSecurity layer with client isolation and encryption in transit and at rest.\nWe do not expose source code or internal prompts in public materials.",
    },
    {
      title_ar: "خطة تطوير المنتج",
      title_en: "Product Roadmap",
      content_ar: "المرحلة الأولى: خدمة مخصصة للمكاتب الهندسية مع SOPs وSLA.\nالمرحلة الثانية: قوالب workflow قابلة للتكرار حسب نوع العميل.\nالمرحلة الثالثة: لوحة عميل بسيطة تعرض حالة الأتمتة والتنبيهات.\nالمرحلة الرابعة: Micro-SaaS لقطاع هندسي ضيق ثم توسع محسوب.\nلا ننتقل إلى منتج قبل أن تثبت الخدمة قيمتها وتوثق أنماط الاستخدام.",
      content_en: "Phase one: customized service for engineering firms with SOPs and SLA.\nPhase two: repeatable workflow templates by client type.\nPhase three: simple client dashboard showing automation status and alerts.\nPhase four: Micro-SaaS for a narrow engineering segment, then measured expansion.\nWe do not move to product before service proves value and usage patterns are documented.",
    },
    {
      title_ar: "إدارة المخاطر",
      title_en: "Risk Management",
      content_ar: "نصنف المخاطر إلى تشغيلية، تقنية، سوقية، تنظيمية، مالية، قانونية، جودة، وأمنية.\nكل خطر له احتمال وأثر وخطة تخفيف قابلة للتنفيذ.\nأخطر المخاطر حالياً هي اعتماد العميل وتغير النطاق، لا نقص التقنية.\nنستخدم Error Node كخط دفاع أول ضد الصمت التشغيلي.\nالمراجعة القانونية والشرعية ليست مرحلة أخيرة، بل شرط قبل التعاقد.",
      content_en: "We classify risks into operational, technical, market, regulatory, financial, legal, quality, and security.\nEach risk has probability, impact, and an executable mitigation plan.\nThe most serious current risks are client adoption and scope creep, not technology shortage.\nWe use Error Node as a first line of defense against operational silence.\nLegal and Sharia review is not a final stage; it is a precondition before contracting.",
    },
    {
      title_ar: "الفريق المؤسس",
      title_en: "Founding Team",
      content_ar: "عمر محمد جميل باعبدالله: المؤسس التشغيلي ومعمار الأنظمة، خلفية هندسية وخبرة SABIC.\nأحمد: الشريك القانوني في ماليزيا، مسؤول عن التأسيس والامتثال المحلي.\nد.سين: مدير العمليات الآلي، يوثق القرارات ويتابع SOPs ويمنع فقدان المعرفة.\nالفريق الحالي صغير عمداً لتقليل Burn Rate وحماية التركيز.\nالتوظيف يأتي بعد الإيراد، لا قبله.",
      content_en: "Omar Mohammed Jamil Baabdullah: operational founder and systems architect, engineering background and SABIC experience.\nAhmed: legal partner in Malaysia, responsible for local formation and compliance.\nDr. Seen: AI operations manager, documenting decisions, following SOPs, and preventing knowledge loss.\nThe current team is intentionally small to reduce burn rate and protect focus.\nHiring comes after revenue, not before it.",
    },
    {
      title_ar: "الامتثال الشرعي والقانوني",
      title_en: "Sharia & Legal Compliance",
      content_ar: "الوكالة تعمل ضمن حدود حلال 100%: لا ربا، لا قطاعات محرمة، لا مشاريع مشبوهة.\nهيكل الاستثمار مقترح كمضاربة شرعية متوافقة مع معايير AAOIFI.\nالعقود تشمل NDA، MSA، SOW، SLA، وDPA حسب طبيعة العميل.\nنلتزم بأنظمة حماية البيانات مثل PDPL حيثما انطبق.\nلا نستخدم وعوداً مالية غير قابلة للتحقق ولا أساليب ضغط في البيع.",
      content_en: "The agency operates within 100 percent Halal boundaries: no riba, no prohibited sectors, no suspicious ventures.\nThe investment structure is proposed as Sharia-compliant Mudarabah aligned with AAOIFI standards.\nContracts include NDA, MSA, SOW, SLA, and DPA depending on client nature.\nWe comply with data protection regulations such as PDPL where applicable.\nWe do not use unverifiable financial promises or pressure tactics in sales.",
    },
    {
      title_ar: "دراسة الجدوى المالية",
      title_en: "Financial Feasibility",
      content_ar: "الجدوى تعتمد على إيراد متكرر من اشتراكات صيانة بعد التأسيس.\nلا ندرج رواتب موظفين في المرحلة الأولى، ما يخفض النقطة الحرجة للتكلفة الثابتة.\nالعتاد يعتبر أصلاً شركياً لا مصروفاً استهلاكياً فقط.\nR&D والخوادم ضرورية لإثبات المنتج قبل التوسع.\nالتسويق محدود وموجه، لا إنفاق عشوائي.\nأي تغيير في التسعير أو هيكل التمويل يتطلب موافقة المؤسس.",
      content_en: "Feasibility relies on recurring revenue from maintenance subscriptions after setup.\nWe do not include employee salaries in the first stage, lowering the critical fixed-cost threshold.\nHardware is treated as a company asset, not merely consumable expense.\nR&D and infrastructure are necessary to prove the product before scaling.\nMarketing is targeted and limited, not random spending.\nAny change in pricing or funding structure requires founder approval.",
    },
    {
      title_ar: "توزيع رأس المال الاستثماري",
      title_en: "Use of Funds",
      content_ar: "67 بالمئة: عتاد وأجهزة، نحو 10,000 دولار.\n20 بالمئة: بحث وتطوير وخوادم، نحو 3,000 دولار.\n13 بالمئة: تسويق واستحواذ، نحو 2,000 دولار.\n0 بالمئة: رواتب موظفين في هذه المرحلة.\nهذا التوزيع يحمي السيولة ويركز على بناء أصل تقني قابل للتسليم.\nالإنفاق يخضع لسجل قرارات وفواتير ومراجعة شهرية.",
      content_en: "67 percent: hardware and equipment, about USD 10,000.\n20 percent: research, development, and infrastructure, about USD 3,000.\n13 percent: marketing and acquisition, about USD 2,000.\n0 percent: employee salaries at this stage.\nThis allocation protects liquidity and focuses on building a deliverable technical asset.\nSpending is subject to a decision log, invoices, and monthly review.",
    },
    {
      title_ar: "معايير الجودة والضمان",
      title_en: "Quality Assurance",
      content_ar: "كل workflow يمر باختبار هلوسة واختبار حالات حدية.\nنستخدم 100 سؤال هلوسة كحد أدنى قبل أي إصدار.\nنحاكي 25 هجمة أمنية قبل التسليم.\nالمخرجات الحرجة لا تُسلم بدون مراجعة بشرية أو قاعدة تحقق.\nالجودة ليست كمالياً، بل حماية لسمعة العميل والوكالة.",
      content_en: "Every workflow passes hallucination testing and edge-case testing.\nWe use 100 hallucination questions as a minimum before any release.\nWe simulate 25 security attacks before delivery.\nCritical outputs are not delivered without human review or validation rules.\nQuality is not perfectionism; it is protection of client and agency reputation.",
    },
    {
      title_ar: "خطط التوسع المستقبلية",
      title_en: "Scaling Plans",
      content_ar: "التوسع يبدأ من الهندسة إلى الطب ثم القانون ثم التعليم ثم التجارة.\nلا ندخل قطاعاً جديداً قبل نجاح القطاع الحالي وتوثيق أنماطه.\nالتوسع الجغرافي ثنائي: السعودية وماليزيا أولاً.\nالمنتج يأتي بعد الخدمة، لا قبلها.\nأي شراكة أو عميل جديد يتطلب مراجعة استراتيجية من المؤسس.",
      content_en: "Expansion starts from engineering to medical, then legal, education, and commerce.\nWe do not enter a new sector before the current sector succeeds and its patterns are documented.\nGeographic expansion is dual: Saudi Arabia and Malaysia first.\nProduct comes after service, not before it.\nAny partnership or new client requires strategic review by the founder.",
    },
    {
      title_ar: "النماذج الأولية وحالات الاستخدام",
      title_en: "Prototypes & Use Cases",
      content_ar: "النموذج الأولي يركز على RFI tracker وQOO compiler وتقرير تقدم أسبوعي.\nحالة الاستخدام الأولى: مكتب هندسي صغير يعاني من تأخر الرد على RFIs.\nالمقياس الناجح ليس عدد الأتمتات، بل ساعات المهندسين المحررة.\nكل حالة استخدام توثق كـ SOP قابل للتكرار.\nلا نعرض بيانات عميل حقيقي قبل NDA وموافقة.",
      content_en: "The prototype focuses on RFI tracker, QOO compiler, and weekly progress report.\nFirst use case: a small engineering firm suffering from delayed RFI responses.\nThe success metric is not number of automations, but engineer hours liberated.\nEach use case is documented as a repeatable SOP.\nWe do not show real client data before NDA and approval.",
    },
    {
      title_ar: "الحوكمة واتخاذ القرار",
      title_en: "Governance & Decision Making",
      content_ar: "القرارات الاستراتيجية والتسعير والتعاقد تتطلب موافقة المؤسس.\nالقرارات التشغيلية اليومية يمكن أن ينفذها د.سين ضمن صلاحياته.\nكل قرار يسجل في DECISION_LOG مع السبب والبديل والنتيجة.\nكل خطأ يوثق في سجل الأخطاء ويحول إلى SOP أو فحص وقائي.\nالشفافية الداخلية تحمي من تكرار الخطأ ومن فقدان المعرفة.",
      content_en: "Strategic decisions, pricing, and contracting require founder approval.\nDaily operational decisions can be executed by Dr. Seen within delegated authority.\nEvery decision is recorded in DECISION_LOG with reason, alternative, and outcome.\nEvery error is documented in the error log and transformed into an SOP or preventive check.\nInternal transparency protects against repeated mistakes and knowledge loss.",
    },
    {
      title_ar: "الدعوة للاستثمار والشراكة",
      title_en: "Investment & Partnership Call",
      content_ar: "نبحث عن شريك يفهم أن بناء شركة تقنية خدمية يحتاج انضباطاً لا ضجيجاً.\nالعرض ليس ربحاً سريعاً، بل أصل قابل للنمو مع مخاطر موثقة.\nالمستثمر يحصل على حقيبة بيانات، خطة عمل، نموذج مالي، وغرفة بيانات فهرسة.\nالوصول الكامل للملفات الحساسة يكون بعد NDA ومراجعة مباشرة.\nالخطوة التالية: اجتماع تشخيصي قصير ثم مذكرة شروط غير ملزمة.",
      content_en: "We seek a partner who understands that building a tech-enabled service company requires discipline, not noise.\nThe offer is not quick profit, but a growable asset with documented risks.\nThe investor receives a data briefcase, business plan, financial model, and indexed data room.\nFull access to sensitive files occurs after NDA and direct review.\nNext step: a short diagnostic meeting, then a non-binding term memo.",
    },
  ],
  pitchSlides: [
    { title_ar: "الغلاف", title_en: "Cover", content_ar: "Seen Automation\nAutomate. Elevate. Halal.", content_en: "Seen Automation\nAutomate. Elevate. Halal." },
    { title_ar: "المشكلة", title_en: "Problem", content_ar: "7.6 ساعة/أسبوع مهدرة\n67.6% أخطاء رسومات", content_en: "7.6 hours/week wasted\n67.6% drawing errors" },
    { title_ar: "الحل", title_en: "Solution", content_ar: "AI Backend Pipelines\nZero-Friction", content_en: "AI Backend Pipelines\nZero-Friction" },
    { title_ar: "لماذا الآن", title_en: "Why Now", content_ar: "Vision 2030\n+56.25% AI spending", content_en: "Vision 2030\n+56.25% AI spending" },
    { title_ar: "السوق", title_en: "Market", content_ar: "TAM $3.5B\nSAM $1.95B\nSOM $320K", content_en: "TAM $3.5B\nSAM $1.95B\nSOM $320K" },
    { title_ar: "النموذج", title_en: "Model", content_ar: "SAR 600-5K/شهر\nهامش 70-80%", content_en: "SAR 600-5K/mo\n70-80% margin" },
    { title_ar: "الجاهزية", title_en: "Readiness", content_ar: "49 ملف\nبروتوكول أمني", content_en: "49 docs\nSecurity protocol" },
    { title_ar: "المنافسون", title_en: "Competitors", content_ar: "Seen: SAR 600-5K + حلال", content_en: "Seen: SAR 600-5K + Halal" },
    { title_ar: "الميزة", title_en: "Edge", content_ar: "حلال 100%\nSLA 5-30 دقيقة", content_en: "100% Halal\nSLA 5-30 min" },
    { title_ar: "الدخول", title_en: "GTM", content_ar: "Landing Bot\nClose 25-35%", content_en: "Landing Bot\nClose 25-35%" },
    { title_ar: "الفريق", title_en: "Team", content_ar: "عمر باعبدالله\nSEGi + SABIC", content_en: "Omar Baabdullah\nSEGi + SABIC" },
    { title_ar: "المالية", title_en: "Financials", content_ar: "Y3: SAR 936K\n80 عميل", content_en: "Y3: SAR 936K\n80 clients" },
    { title_ar: "الطلب", title_en: "Ask", content_ar: "SAR 82,500\nمضاربة شرعية", content_en: "SAR 82,500\nSharia Mudarabah" },
    { title_ar: "الرؤية", title_en: "Vision", content_ar: "Y5: 200+ عميل\n$2M+ ARR", content_en: "Y5: 200+ clients\n$2M+ ARR" },
  ],
  securityHighlights: { attacks: 25, hallucinationTests: 100, encryption: "AES-256 + TLS 1.3" },
  checklists: {
    investorReady: [
      { label_ar: "خطة عمل شاملة", label_en: "Comprehensive business plan", done: true },
      { label_ar: "نموذج مالي تفاعلي", label_en: "Interactive financial model", done: true },
      { label_ar: "Pitch Deck (14 شريحة)", label_en: "Pitch Deck (14 slides)", done: true },
      { label_ar: "تحليل المنافسين", label_en: "Competitor analysis", done: true },
      { label_ar: "5 قطاعات مستهدفة", label_en: "5 target sectors", done: true },
      { label_ar: "خريطة طريق 36 شهر", label_en: "36-month roadmap", done: true },
      { label_ar: "سجل مخاطر", label_en: "Risk register", done: true },
      { label_ar: "مواصفات عتاد", label_en: "Hardware specs", done: true },
      { label_ar: "مضاربة شرعية", label_en: "Sharia Mudarabah", done: true },
      { label_ar: "بروتوكول أمني", label_en: "Security protocol", done: true },
    ],
    dueDiligence: [
      { label_ar: "NDA Template", label_en: "NDA Template", done: true },
      { label_ar: "MSA Template", label_en: "MSA Template", done: true },
      { label_ar: "SOW Template", label_en: "SOW Template", done: true },
      { label_ar: "SLA Template", label_en: "SLA Template", done: true },
      { label_ar: "DPA Template", label_en: "DPA Template", done: true },
      { label_ar: "Unit Economics", label_en: "Unit Economics", done: true },
      { label_ar: "Market Positioning", label_en: "Market Positioning", done: true },
      { label_ar: "Halal Certification", label_en: "Halal Certification", done: true },
    ],
  },
  dataSources: [
    { title: "Saudi Arabia Artificial Intelligence Market Report 2025-2032", publisher: "MarketsandMarkets", url: "https://www.marketsandmarkets.com/Market-Reports/saudi-arabia-artificial-intelligence-market-160864989.html", accessed: "2026-10-09", note: "TAM context for Saudi AI market growth." },
    { title: "Saudi Arabia Artificial Intelligence Market Size Report 2033", publisher: "Grand View Research", url: "https://www.grandviewresearch.com/industry-analysis/saudi-arabia-artificial-intelligence-market-report", accessed: "2026-10-09", note: "Broad Saudi AI market sizing." },
    { title: "Saudi Arabia Artificial Intelligence Market 2034", publisher: "IMARC Group", url: "https://www.imarcgroup.com/saudi-arabia-artificial-intelligence-market", accessed: "2026-10-09", note: "Alternative Saudi AI market estimate and CAGR." },
    { title: "U.S. Companies Ramp Up Automation and AI as Inflation", publisher: "Richmond Fed CFO Survey", url: "https://www.richmondfed.org/research/national_economy/cfo_survey/data_and_results/2024/20240620_data_and_results", accessed: "2026-10-09", note: "Around 60 percent of firms implemented automation in last 12 months." },
    { title: "UiPath Announces Investments in Saudi Arabia", publisher: "UiPath Investor Relations", url: "https://ir.uipath.com/news/detail/328/uipath-announces-investments-in-saudi-arabia-including-first-saudi-school-of-automation-and-new-office-location-in-riyadh", accessed: "2026-10-09", note: "Competitor market validation in Saudi Arabia." },
    { title: "UiPath Dominates the RPA Space", publisher: "CX Today", url: "https://cxtoday.com/uipath-dominates-the-rpa-space-dwarfs-microsofts-market-share-by-10x", accessed: "2026-10-09", note: "UiPath RPA market share context." },
    { title: "Malaysia Business Process Management Market", publisher: "IMARC Group", url: "https://www.imarcgroup.com/malaysia-business-process-management-market", accessed: "2026-10-09", note: "Malaysia BPM market size and CAGR." },
    { title: "Malaysia Marketing Automation Market 2025-2030", publisher: "MarketsandMarkets", url: "https://www.marketsandmarkets.com/Market-Reports/geography/marketing-automation-software-market/malaysia", accessed: "2026-10-09", note: "Malaysia automation adjacent market." },
    { title: "Enhancing RFI Process in Construction through Digitalization", publisher: "ResearchGate", url: "https://www.researchgate.net/publication/400511138_Enhancing_Request_for_Information_RFI_Process_in_Construction_through_Digitalization_and_Automation", accessed: "2026-10-09", note: "RFI automation reduces manual processing time." },
    { title: "SaaS Pricing Benchmark Study 2025", publisher: "Monetizely", url: "https://www.getmonetizely.com/articles/saas-pricing-benchmark-study-2025-key-insights-from-100-companies-analyzed", accessed: "2026-10-09", note: "Pricing model benchmark context." },
  ],
};
